/*
 * The catalogue the recommender draws from.
 *
 * Each game has:
 *   id         unique slug, used in shareable links
 *   title      display name
 *   year       release year of this version
 *   series     optional; games in the same series get a small nudge together
 *   platforms  where this version is sold natively (see PLATFORMS below)
 *   hours      rough main-story length, in the spirit of HowLongToBeat's "Main Story" figure
 *   tags       taste tags (see TAGS below); these drive the matching
 *   pitch      one sentence shown on the results card
 *   aka        optional search aliases
 *   starter    optional; widely loved, approachable picks used when there is little to go on
 *   note       optional; shown under the platforms line
 *
 * Backward compatibility is handled in recommend.js, so a PS4 game only needs "ps4"
 * to show up for someone with a PS5, an Xbox One game shows up on Series X|S, and a
 * Switch game shows up on Switch 2.
 */
window.RPG_DATA = {
  updated: "October 2026",

  platforms: [
    { key: "pc", label: "PC or Steam Deck", short: "PC" },
    { key: "ps5", label: "PlayStation 5", short: "PS5" },
    { key: "ps4", label: "PlayStation 4", short: "PS4" },
    { key: "xsx", label: "Xbox Series X|S", short: "Xbox Series" },
    { key: "xb1", label: "Xbox One", short: "Xbox One" },
    { key: "switch2", label: "Nintendo Switch 2", short: "Switch 2" },
    { key: "switch", label: "Nintendo Switch", short: "Switch" },
    { key: "mobile", label: "Phone or tablet", short: "Mobile" },
    { key: "snes", label: "Super Nintendo", short: "SNES" },
    { key: "megadrive", label: "Sega Mega Drive", short: "Mega Drive" },
    { key: "ps1", label: "PlayStation 1", short: "PS1" },
    { key: "saturn", label: "Sega Saturn", short: "Saturn" },
    { key: "n64", label: "Nintendo 64", short: "N64" }
  ],

  // label: how the tag reads in a sentence; mood: offered as an "in the mood for" option
  tags: {
    "turn-based": { label: "turn-based battles", mood: "Turn-based battles", group: "play" },
    "action": { label: "real-time action combat", mood: "Real-time action", group: "play" },
    "tactics": { label: "grid-based tactics", mood: "Grid tactics", group: "play" },
    "rtwp": { label: "real-time-with-pause combat", mood: "Real-time with pause", group: "play" },
    "no-combat": { label: "little or no combat", mood: "Little or no combat", group: "play" },
    "open-world": { label: "an open world", mood: "Open world", group: "play" },
    "builds": { label: "deep character builds", mood: "Deep character builds", group: "play" },
    "challenge": { label: "a tough challenge", mood: "A tough challenge", group: "play" },
    "loot": { label: "plenty of loot to chase", mood: "Loot hunting", group: "play" },
    "roguelite": { label: "roguelite runs" },
    "exploration": { label: "lots to explore" },
    "party": { label: "a party of companions" },
    "solo": { label: "a solo hero" },
    "jrpg": { label: "a JRPG style", mood: "JRPG style", group: "feel" },
    "crpg": { label: "classic PC RPG roots", mood: "Classic PC RPG style", group: "feel" },
    "story": { label: "a strong story", mood: "A strong story", group: "feel" },
    "choices": { label: "choices that matter", mood: "Choices that matter", group: "feel" },
    "social": { label: "friendships and daily life", mood: "Friendships and daily life", group: "feel" },
    "humour": { label: "a sense of humour", mood: "Something funny", group: "feel" },
    "cosy": { label: "a cosy feel", mood: "Something cosy", group: "feel" },
    "emotional": { label: "an emotional punch", mood: "Something moving", group: "feel" },
    "retro": { label: "a retro look", mood: "Retro pixel art", group: "feel" },
    "fantasy": { label: "a fantasy world" },
    "dark-fantasy": { label: "a dark fantasy world", mood: "Dark fantasy", group: "feel" },
    "sci-fi": { label: "a sci-fi setting", mood: "Sci-fi", group: "feel" },
    "post-apoc": { label: "a post-apocalyptic setting" },
    "modern": { label: "a modern-day setting" },
    "historical": { label: "a historical setting", mood: "Historical setting", group: "feel" },
    "surreal": { label: "a surreal streak" }
  },

  games: [
    // Open worlds and western action RPGs
    { id: "witcher3", title: "The Witcher 3: Wild Hunt", year: 2015, series: "witcher", platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 50,
      tags: ["action", "open-world", "solo", "dark-fantasy", "story", "choices", "exploration"], starter: true, aka: ["witcher"],
      pitch: "A monster hunter searches for his adopted daughter across a war-torn, beautifully written open world." },
    { id: "skyrim", title: "The Elder Scrolls V: Skyrim", year: 2011, series: "elder-scrolls", platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 34,
      tags: ["action", "open-world", "solo", "fantasy", "exploration", "builds"], starter: true, aka: ["tes", "elder scrolls"],
      pitch: "Pick a direction and start walking; the classic sandbox where your own detours become the story." },
    { id: "oblivion-r", title: "The Elder Scrolls IV: Oblivion Remastered", year: 2025, series: "elder-scrolls", platforms: ["pc", "ps5", "xsx"], hours: 28,
      tags: ["action", "open-world", "solo", "fantasy", "exploration", "builds", "humour"], aka: ["oblivion", "tes"],
      pitch: "A rebuilt take on the 2006 classic, with brilliant guild questlines and a gloriously odd sense of humour." },
    { id: "cyberpunk", title: "Cyberpunk 2077", year: 2020, platforms: ["pc", "ps5", "xsx", "switch2"], hours: 26,
      tags: ["action", "open-world", "solo", "sci-fi", "story", "builds", "exploration"], starter: true, aka: ["2077"],
      pitch: "A dense neon city and sharp character writing, long since rebuilt after its rocky launch; the Phantom Liberty expansion is worth it." },
    { id: "fnv", title: "Fallout: New Vegas", year: 2010, series: "fallout", platforms: ["pc", "xb1"], hours: 27,
      tags: ["action", "open-world", "solo", "post-apoc", "choices", "humour", "builds"], aka: ["new vegas", "fallout nv"], note: "Xbox via backward compatibility",
      pitch: "Many fans' favourite Fallout: faction politics, sharp writing, and choices with real consequences." },
    { id: "fallout4", title: "Fallout 4", year: 2015, series: "fallout", platforms: ["pc", "ps4", "xb1"], hours: 27,
      tags: ["action", "open-world", "solo", "post-apoc", "exploration", "loot", "builds"],
      pitch: "A huge ruined Boston to scavenge, with settlement building and satisfying gunplay." },
    { id: "outer-worlds", title: "The Outer Worlds", year: 2019, series: "outer-worlds", platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 14,
      tags: ["action", "party", "sci-fi", "humour", "choices", "story"],
      pitch: "A compact, satirical space romp from Obsidian; Fallout energy in a fraction of the hours." },
    { id: "starfield", title: "Starfield", year: 2023, platforms: ["pc", "xsx"], hours: 23,
      tags: ["action", "open-world", "solo", "sci-fi", "exploration", "builds"],
      pitch: "Bethesda's space sandbox: build ships, join factions, and land on more planets than you will ever finish." },
    { id: "avowed", title: "Avowed", year: 2025, platforms: ["pc", "xsx"], hours: 25,
      tags: ["action", "solo", "fantasy", "story", "choices", "exploration"],
      pitch: "Obsidian's first-person fantasy set in the Pillars of Eternity world, with lively spell-and-sword combat." },
    { id: "kcd", title: "Kingdom Come: Deliverance", year: 2018, series: "kcd", platforms: ["pc", "ps4", "xb1", "switch"], hours: 42,
      tags: ["action", "open-world", "solo", "historical", "challenge", "story"], aka: ["kcd"],
      pitch: "Medieval Bohemia with no magic and no dragons, where you start out genuinely bad at everything." },
    { id: "kcd2", title: "Kingdom Come: Deliverance II", year: 2025, series: "kcd", platforms: ["pc", "ps5", "xsx"], hours: 55,
      tags: ["action", "open-world", "solo", "historical", "story", "challenge", "humour", "exploration"], aka: ["kcd2", "kcd 2"],
      pitch: "A bigger, funnier, more confident sequel and one of the most immersive historical worlds in games." },
    { id: "dd2", title: "Dragon's Dogma 2", year: 2024, series: "dragons-dogma", platforms: ["pc", "ps5", "xsx"], hours: 30,
      tags: ["action", "open-world", "party", "fantasy", "exploration", "builds"],
      pitch: "Clamber up giant monsters with a party of AI companions and let the open world surprise you." },
    { id: "dd1", title: "Dragon's Dogma: Dark Arisen", year: 2016, series: "dragons-dogma", platforms: ["pc", "ps4", "xb1", "switch"], hours: 35,
      tags: ["action", "open-world", "party", "fantasy", "exploration", "builds"],
      pitch: "The cult original: the same monster climbing and helper companions in a scrappier package." },
    { id: "hogwarts", title: "Hogwarts Legacy", year: 2023, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch2", "switch"], hours: 26,
      tags: ["action", "open-world", "solo", "fantasy", "exploration", "cosy"],
      pitch: "Wander a lovingly detailed wizarding school and the countryside around it at your own pace." },
    { id: "horizon-zd", title: "Horizon Zero Dawn", year: 2017, series: "horizon", platforms: ["pc", "ps5", "ps4"], hours: 22,
      tags: ["action", "open-world", "solo", "sci-fi", "exploration", "story"],
      pitch: "Hunt robotic beasts across a lush post-apocalyptic wilderness, with a central mystery that pays off." },
    { id: "amalur", title: "Kingdoms of Amalur: Re-Reckoning", year: 2020, platforms: ["pc", "ps4", "xb1", "switch"], hours: 40,
      tags: ["action", "open-world", "solo", "fantasy", "loot", "builds", "exploration"], aka: ["amalur"],
      pitch: "Big, colourful fantasy with punchy combat and a flexible class system; proper comfort food." },
    { id: "vtmb", title: "Vampire: The Masquerade - Bloodlines", year: 2004, platforms: ["pc"], hours: 30,
      tags: ["action", "solo", "modern", "dark-fantasy", "story", "choices", "humour"], aka: ["bloodlines", "vtmb"],
      pitch: "A janky but beloved cult classic about vampire politics in night-time Los Angeles, with superb writing." },

    // Soulslikes and action RPGs
    { id: "elden-ring", title: "Elden Ring", year: 2022, series: "souls", platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch2"], hours: 60,
      tags: ["action", "open-world", "solo", "dark-fantasy", "challenge", "exploration", "builds"], starter: true,
      pitch: "FromSoftware's open-world epic: brutal bosses, a vast mysterious map, and total freedom over where to go next." },
    { id: "ds-r", title: "Dark Souls Remastered", year: 2018, series: "souls", platforms: ["pc", "ps4", "xb1", "switch"], hours: 42,
      tags: ["action", "solo", "dark-fantasy", "challenge", "exploration", "builds"], aka: ["dark souls 1"],
      pitch: "The unforgiving original that defined a genre, with an interlocking world where every shortcut feels earned." },
    { id: "ds3", title: "Dark Souls III", year: 2016, series: "souls", platforms: ["pc", "ps4", "xb1"], hours: 32,
      tags: ["action", "solo", "dark-fantasy", "challenge", "builds"], aka: ["ds3"],
      pitch: "Faster and more aggressive than its predecessors, with some of the best boss fights FromSoftware has made." },
    { id: "bloodborne", title: "Bloodborne", year: 2015, series: "souls", platforms: ["ps4"], hours: 33,
      tags: ["action", "solo", "dark-fantasy", "challenge", "exploration"],
      pitch: "Gothic horror with a fast combat style that rewards you for attacking rather than hiding behind a shield." },
    { id: "demons-souls", title: "Demon's Souls", year: 2020, series: "souls", platforms: ["ps5"], hours: 25,
      tags: ["action", "solo", "dark-fantasy", "challenge"],
      pitch: "A gorgeous remake of the game that started it all; compact, tense, and a showcase for the PS5." },
    { id: "lies-of-p", title: "Lies of P", year: 2023, platforms: ["pc", "ps5", "ps4", "xsx", "xb1"], hours: 30,
      tags: ["action", "solo", "dark-fantasy", "challenge", "builds"],
      pitch: "A dark Pinocchio retelling with tight, parry-focused combat; one of the best soulslikes not made by FromSoftware." },
    { id: "nioh2", title: "Nioh 2", year: 2020, platforms: ["pc", "ps5", "ps4"], hours: 50,
      tags: ["action", "solo", "dark-fantasy", "historical", "challenge", "builds", "loot"],
      pitch: "A samurai soulslike with layered combat stances and a deep loot game for build tinkerers." },
    { id: "diablo4", title: "Diablo IV", year: 2023, platforms: ["pc", "ps5", "ps4", "xsx", "xb1"], hours: 25,
      tags: ["action", "solo", "dark-fantasy", "loot", "builds"], aka: ["diablo 4"],
      pitch: "Slick, gothic loot chasing with a surprisingly strong campaign, and an endless endgame if you want one." },
    { id: "grim-dawn", title: "Grim Dawn", year: 2016, platforms: ["pc", "xb1"], hours: 45,
      tags: ["action", "solo", "dark-fantasy", "loot", "builds", "challenge"],
      pitch: "A deep, old-school action RPG for theorycrafters, with dual classes and an enormous item pool." },
    { id: "torchlight2", title: "Torchlight II", year: 2012, platforms: ["pc", "ps4", "xb1", "switch"], hours: 20,
      tags: ["action", "solo", "fantasy", "loot", "builds", "cosy"],
      pitch: "Bright, approachable loot chasing; Diablo with the edges sanded off." },
    { id: "hades", title: "Hades", year: 2020, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 22,
      tags: ["action", "solo", "roguelite", "fantasy", "story", "challenge", "builds"],
      pitch: "Fight your way out of the underworld again and again; every run moves the story and your power forward." },

    // Party-based western RPGs
    { id: "bg3", title: "Baldur's Gate 3", year: 2023, series: "baldurs-gate", platforms: ["pc", "ps5", "xsx"], hours: 70,
      tags: ["turn-based", "party", "crpg", "fantasy", "story", "choices", "builds", "humour"], starter: true, aka: ["bg3", "baldurs gate"],
      pitch: "Dungeons & Dragons brought to life: a sprawling party adventure where nearly any plan you come up with actually works." },
    { id: "bg2", title: "Baldur's Gate II: Enhanced Edition", year: 2013, series: "baldurs-gate", platforms: ["pc", "ps4", "xb1", "switch", "mobile"], hours: 60,
      tags: ["rtwp", "party", "crpg", "fantasy", "story", "builds", "retro"], aka: ["bg2"],
      pitch: "The real-time-with-pause epic, with a legendary villain and companions people still talk about decades later." },
    { id: "dos2", title: "Divinity: Original Sin 2", year: 2017, platforms: ["pc", "ps4", "xb1", "switch"], hours: 60,
      tags: ["turn-based", "party", "crpg", "fantasy", "choices", "builds", "humour", "challenge"], aka: ["dos2", "divinity"],
      pitch: "Larian's systemic playground before Baldur's Gate 3, built on elemental combos and co-op chaos." },
    { id: "pillars", title: "Pillars of Eternity", year: 2015, series: "pillars", platforms: ["pc", "ps4", "xb1", "switch"], hours: 37,
      tags: ["rtwp", "party", "crpg", "fantasy", "story", "builds"], aka: ["poe"],
      pitch: "A love letter to the Infinity Engine classics, with thoughtful writing about souls and faith." },
    { id: "deadfire", title: "Pillars of Eternity II: Deadfire", year: 2018, series: "pillars", platforms: ["pc", "ps4", "xb1", "switch"], hours: 45,
      tags: ["rtwp", "party", "crpg", "fantasy", "exploration", "builds", "choices"], aka: ["poe2", "deadfire"],
      pitch: "Pirate-flavoured island hopping with ship battles, rival factions, and an optional turn-based mode." },
    { id: "wotr", title: "Pathfinder: Wrath of the Righteous", year: 2021, platforms: ["pc", "ps4", "xb1"], hours: 75,
      tags: ["rtwp", "turn-based", "party", "crpg", "fantasy", "builds", "choices", "challenge"], aka: ["pathfinder", "wotr"],
      pitch: "A crusade against demons with absurdly deep character building and mythic paths that reshape your story." },
    { id: "rogue-trader", title: "Warhammer 40,000: Rogue Trader", year: 2023, platforms: ["pc", "ps5", "xsx"], hours: 70,
      tags: ["turn-based", "party", "crpg", "sci-fi", "choices", "builds", "story"], aka: ["40k", "rogue trader"],
      pitch: "Run a starship dynasty in the grim far future, with tactical turn-based fights and weighty choices." },
    { id: "wasteland3", title: "Wasteland 3", year: 2020, platforms: ["pc", "ps4", "xb1"], hours: 40,
      tags: ["turn-based", "party", "crpg", "post-apoc", "choices", "humour", "builds"],
      pitch: "Squad-based survival in a frozen, post-apocalyptic Colorado, with dark humour and tough moral calls." },
    { id: "shadowrun-df", title: "Shadowrun: Dragonfall", year: 2014, platforms: ["pc", "ps4", "xb1", "switch"], hours: 25,
      tags: ["turn-based", "party", "crpg", "sci-fi", "story", "choices"], aka: ["shadowrun"], note: "On consoles it comes in the Shadowrun Trilogy",
      pitch: "Cyberpunk meets fantasy in a near-future Berlin, with turn-based tactics and some of the best writing in the genre." },
    { id: "pst", title: "Planescape: Torment Enhanced Edition", year: 2017, platforms: ["pc", "ps4", "xb1", "switch", "mobile"], hours: 30,
      tags: ["rtwp", "party", "crpg", "surreal", "story", "choices", "retro"], aka: ["planescape"],
      pitch: "A philosophical classic about an amnesiac immortal; best for patient players who love to read." },
    { id: "tyranny", title: "Tyranny", year: 2016, platforms: ["pc"], hours: 22,
      tags: ["rtwp", "party", "crpg", "dark-fantasy", "choices", "story"],
      pitch: "Evil has already won and you work for it; a short, reactive story with big branching paths." },
    { id: "mass-effect", title: "Mass Effect Legendary Edition", year: 2021, series: "mass-effect", platforms: ["pc", "ps4", "xb1"], hours: 65,
      tags: ["action", "party", "sci-fi", "story", "choices", "emotional"], starter: true, aka: ["mass effect", "me1", "me2", "me3"],
      pitch: "The full trilogy: build a crew, make hard calls, and watch them echo across three games." },
    { id: "kotor", title: "Star Wars: Knights of the Old Republic", year: 2003, platforms: ["pc", "switch", "mobile"], hours: 30,
      tags: ["rtwp", "party", "sci-fi", "story", "choices", "retro"], aka: ["kotor", "star wars"],
      pitch: "BioWare's classic set thousands of years before the films, with a plot twist that is still talked about." },
    { id: "dao", title: "Dragon Age: Origins", year: 2009, series: "dragon-age", platforms: ["pc", "xb1"], hours: 40,
      tags: ["rtwp", "party", "dark-fantasy", "story", "choices", "builds"], aka: ["dao"], note: "Xbox via backward compatibility",
      pitch: "Gritty fantasy with tactical party combat and companions who will absolutely judge your choices." },
    { id: "dai", title: "Dragon Age: Inquisition", year: 2014, series: "dragon-age", platforms: ["pc", "ps4", "xb1"], hours: 47,
      tags: ["action", "party", "fantasy", "story", "choices", "exploration"], aka: ["dai"],
      pitch: "Lead a growing order across large open zones, backed by a great cast of companions." },
    { id: "veilguard", title: "Dragon Age: The Veilguard", year: 2024, series: "dragon-age", platforms: ["pc", "ps5", "xsx"], hours: 45,
      tags: ["action", "party", "fantasy", "story"],
      pitch: "A brighter, faster, more action-led Dragon Age built around a close-knit crew." },
    { id: "darkest-dungeon", title: "Darkest Dungeon", year: 2016, platforms: ["pc", "ps4", "xb1", "switch"], hours: 45,
      tags: ["turn-based", "party", "dark-fantasy", "challenge", "roguelite", "builds"],
      pitch: "Lead a doomed roster into gothic dungeons, where stress can break your heroes as surely as monsters can." },

    // Narrative-first and short
    { id: "disco", title: "Disco Elysium: The Final Cut", year: 2021, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 22,
      tags: ["no-combat", "crpg", "solo", "surreal", "story", "choices", "humour"], starter: true, aka: ["disco elysium"],
      pitch: "A detective RPG with no combat at all, where the arguing voices in your own head are the party." },
    { id: "pentiment", title: "Pentiment", year: 2022, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 18,
      tags: ["no-combat", "solo", "historical", "story", "choices"],
      pitch: "A murder mystery in a 16th-century Bavarian village, illustrated like a living manuscript." },
    { id: "citizen-sleeper", title: "Citizen Sleeper", year: 2022, series: "citizen-sleeper", platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 8,
      tags: ["no-combat", "solo", "sci-fi", "story", "choices", "emotional"],
      pitch: "Dice-driven survival on a decaying space station; a short story about precarity, kindness, and making a life." },
    { id: "citizen-sleeper-2", title: "Citizen Sleeper 2: Starward Vector", year: 2025, series: "citizen-sleeper", platforms: ["pc", "ps5", "xsx", "switch"], hours: 14,
      tags: ["no-combat", "party", "sci-fi", "story", "choices", "emotional"],
      pitch: "A bigger, tenser sequel: gather a crew and keep everyone alive on the run between stations." },
    { id: "undertale", title: "Undertale", year: 2015, platforms: ["pc", "ps4", "xb1", "switch"], hours: 6,
      tags: ["turn-based", "solo", "surreal", "humour", "emotional", "retro"], starter: true,
      pitch: "A short, heartfelt cult hit where you can befriend every monster instead of fighting them." },
    { id: "deltarune", title: "Deltarune", year: 2025, platforms: ["pc", "ps5", "ps4", "switch2", "switch"], hours: 15,
      tags: ["turn-based", "party", "surreal", "humour", "emotional", "retro"], note: "Chapters 1 to 4 so far; more on the way",
      pitch: "The follow-up to Undertale, released in chapters; funnier, stranger, and with a proper party." },
    { id: "omori", title: "OMORI", year: 2020, platforms: ["pc", "ps4", "xb1", "switch"], hours: 20,
      tags: ["turn-based", "party", "surreal", "emotional", "story", "retro"],
      pitch: "A cheerful-looking adventure that slowly becomes an unsettling story about guilt and grief; it deals with heavy themes." },

    // JRPGs
    { id: "clair-obscur", title: "Clair Obscur: Expedition 33", year: 2025, platforms: ["pc", "ps5", "xsx"], hours: 32,
      tags: ["turn-based", "party", "jrpg", "fantasy", "surreal", "story", "emotional", "challenge"], starter: true, aka: ["e33", "expedition 33"],
      pitch: "Belle Époque-inspired fantasy whose turn-based fights you dodge and parry in real time; a standout of 2025." },
    { id: "p5r", title: "Persona 5 Royal", year: 2020, series: "persona", platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 100,
      tags: ["turn-based", "party", "jrpg", "modern", "social", "story"], starter: true, aka: ["p5r", "persona 5", "p5"],
      pitch: "Stylish phantom thieves in modern Tokyo: dungeon crawling by night, school life and friendships by day." },
    { id: "p4g", title: "Persona 4 Golden", year: 2012, series: "persona", platforms: ["pc", "ps4", "xb1", "switch"], hours: 55,
      tags: ["turn-based", "party", "jrpg", "modern", "social", "story", "humour"], aka: ["p4g", "persona 4", "p4"],
      pitch: "A small-town murder mystery with one of the warmest casts in any JRPG." },
    { id: "p3r", title: "Persona 3 Reload", year: 2024, series: "persona", platforms: ["pc", "ps5", "ps4", "xsx", "xb1"], hours: 60,
      tags: ["turn-based", "party", "jrpg", "modern", "social", "story", "emotional"], aka: ["p3r", "persona 3", "p3"],
      pitch: "A full remake of the Dark Hour classic; moodier than Persona 5 and quietly devastating." },
    { id: "metaphor", title: "Metaphor: ReFantazio", year: 2024, platforms: ["pc", "ps5", "ps4", "xsx"], hours: 75,
      tags: ["turn-based", "party", "jrpg", "fantasy", "social", "story"], aka: ["refantazio"],
      pitch: "Atlus's fantasy election epic, with a Persona-style calendar and bonds wrapped around a political journey." },
    { id: "smt5v", title: "Shin Megami Tensei V: Vengeance", year: 2024, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 55,
      tags: ["turn-based", "party", "jrpg", "post-apoc", "challenge", "builds"], aka: ["smt", "smt5", "smt v"],
      pitch: "Recruit and fuse demons in punishing battles where exploiting weaknesses is everything." },
    { id: "ff7r", title: "Final Fantasy VII Remake Intergrade", year: 2021, series: "ff7-remake", platforms: ["pc", "ps5", "xsx", "switch2"], hours: 34,
      tags: ["action", "party", "jrpg", "sci-fi", "story"], starter: true, aka: ["ff7", "ffvii", "ff7 remake", "final fantasy 7"],
      pitch: "The first part of the remake trilogy, expanding Midgar into a full game with hybrid action and command combat." },
    { id: "ff7rb", title: "Final Fantasy VII Rebirth", year: 2024, series: "ff7-remake", platforms: ["pc", "ps5"], hours: 45,
      tags: ["action", "party", "jrpg", "open-world", "fantasy", "story", "exploration"], aka: ["ff7", "ffvii", "rebirth", "final fantasy 7"],
      pitch: "The trilogy's second part opens up into huge regions full of side content, minigames, and party banter." },
    { id: "ff7", title: "Final Fantasy VII", year: 1997, platforms: ["pc", "ps4", "xb1", "switch", "mobile", "ps1"], hours: 37,
      tags: ["turn-based", "party", "jrpg", "sci-fi", "story", "retro"], aka: ["ff7", "ffvii", "final fantasy 7", "original"],
      pitch: "The 1997 original, still compelling for its materia system and its story about a planet being drained dry." },
    { id: "ff6", title: "Final Fantasy VI Pixel Remaster", year: 2022, platforms: ["pc", "ps4", "xsx", "switch", "mobile"], hours: 35,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "retro", "emotional"], aka: ["ff6", "ffvi", "final fantasy 6"],
      pitch: "Often called the series' peak, with a huge ensemble cast and a world that changes dramatically halfway through." },
    { id: "ff9", title: "Final Fantasy IX", year: 2000, platforms: ["pc", "ps4", "xb1", "switch", "mobile", "ps1"], hours: 40,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "emotional", "retro"], aka: ["ff9", "ffix", "final fantasy 9"],
      pitch: "A warm, storybook return to classic fantasy, with a cast that grows on you and a lot to say about mortality." },
    { id: "ffx", title: "Final Fantasy X HD Remaster", year: 2014, platforms: ["pc", "ps4", "xb1", "switch"], hours: 45,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "emotional"], aka: ["ffx", "ff10", "final fantasy 10"], note: "Sold with X-2 as a bundle",
      pitch: "A pilgrimage across a tropical world, with one of the cleanest turn-based battle systems in the series." },
    { id: "ff12", title: "Final Fantasy XII: The Zodiac Age", year: 2017, platforms: ["pc", "ps4", "xb1", "switch"], hours: 50,
      tags: ["rtwp", "party", "jrpg", "fantasy", "story", "builds", "exploration"], aka: ["ff12", "ffxii", "final fantasy 12"],
      pitch: "Political fantasy in Ivalice, with a gambit system that lets you script exactly how your party fights." },
    { id: "ff15", title: "Final Fantasy XV", year: 2016, platforms: ["pc", "ps4", "xb1"], hours: 28,
      tags: ["action", "party", "jrpg", "open-world", "fantasy", "story"], aka: ["ff15", "ffxv", "final fantasy 15"],
      pitch: "A road trip with four friends across an open world, with fast, warp-striking action combat." },
    { id: "ff16", title: "Final Fantasy XVI", year: 2023, platforms: ["pc", "ps5"], hours: 37,
      tags: ["action", "solo", "dark-fantasy", "story"], aka: ["ff16", "ffxvi", "final fantasy 16"],
      pitch: "A darker, more grown-up Final Fantasy with spectacular action combat and kaiju-sized summon battles." },
    { id: "fft", title: "Final Fantasy Tactics: The Ivalice Chronicles", year: 2025, platforms: ["pc", "ps5", "ps4", "xsx", "switch2", "switch"], hours: 45,
      tags: ["tactics", "party", "jrpg", "fantasy", "story", "builds", "challenge"], aka: ["fft", "final fantasy tactics"],
      pitch: "A rebuilt version of the 1997 tactics classic, with full voice acting and a famously flexible job system." },
    { id: "tactics-ogre", title: "Tactics Ogre: Reborn", year: 2022, platforms: ["pc", "ps5", "ps4", "switch"], hours: 40,
      tags: ["tactics", "party", "jrpg", "fantasy", "choices", "story", "challenge"],
      pitch: "A grounded war story where your decisions fracture the plot, from the team behind Final Fantasy Tactics." },
    { id: "unicorn-overlord", title: "Unicorn Overlord", year: 2024, platforms: ["ps5", "ps4", "xsx", "switch"], hours: 50,
      tags: ["tactics", "party", "jrpg", "fantasy", "builds"],
      pitch: "Vanillaware's army-building strategy RPG: set up squads, write their battle rules, then watch them play out." },
    { id: "fe3h", title: "Fire Emblem: Three Houses", year: 2019, series: "fire-emblem", platforms: ["switch"], hours: 50,
      tags: ["tactics", "party", "jrpg", "fantasy", "social", "story", "choices"], starter: true, aka: ["three houses", "fire emblem"],
      pitch: "Teach a class at a monastery, then lead them into war; the house you choose changes everything." },
    { id: "fe-engage", title: "Fire Emblem Engage", year: 2023, series: "fire-emblem", platforms: ["switch"], hours: 45,
      tags: ["tactics", "party", "jrpg", "fantasy", "challenge"], aka: ["fire emblem"],
      pitch: "The series' best pure combat, with flashy summons of past heroes; the story is lighter." },
    { id: "triangle", title: "Triangle Strategy", year: 2022, platforms: ["pc", "switch"], hours: 40,
      tags: ["tactics", "party", "jrpg", "fantasy", "choices", "story", "retro"],
      pitch: "Pixel-art tactics where your party votes on big decisions and you have to win them round." },
    { id: "live-a-live", title: "Live A Live", year: 2022, platforms: ["pc", "ps5", "ps4", "switch"], hours: 25,
      tags: ["tactics", "party", "jrpg", "retro", "story"],
      pitch: "Short, self-contained chapters set across wildly different eras, from prehistory to the far future." },
    { id: "xc1", title: "Xenoblade Chronicles: Definitive Edition", year: 2020, series: "xenoblade", platforms: ["switch"], hours: 60,
      tags: ["action", "party", "jrpg", "open-world", "fantasy", "exploration", "story"], aka: ["xenoblade"],
      pitch: "Explore landscapes on the bodies of two titanic, long-dead gods, with a fantastic soundtrack along the way." },
    { id: "xc2", title: "Xenoblade Chronicles 2", year: 2017, series: "xenoblade", platforms: ["switch"], hours: 70,
      tags: ["action", "party", "jrpg", "fantasy", "exploration", "story", "builds"], aka: ["xenoblade"],
      pitch: "A sea of clouds and nations on the backs of titans, with a slow-burning combat system that thrills once it clicks." },
    { id: "xc3", title: "Xenoblade Chronicles 3", year: 2022, series: "xenoblade", platforms: ["switch"], hours: 65,
      tags: ["action", "party", "jrpg", "fantasy", "story", "emotional", "exploration"], aka: ["xenoblade"],
      pitch: "Soldiers born to fight for ten years start to wonder whether life could be more; the series' most moving entry." },
    { id: "xcx", title: "Xenoblade Chronicles X: Definitive Edition", year: 2025, series: "xenoblade", platforms: ["switch"], hours: 70,
      tags: ["action", "party", "jrpg", "sci-fi", "open-world", "exploration", "builds"], aka: ["xenoblade x"],
      pitch: "Humanity crash-lands on an alien planet; vast exploration on foot, and later in giant mechs." },
    { id: "dq11", title: "Dragon Quest XI S: Echoes of an Elusive Age", year: 2019, series: "dragon-quest", platforms: ["pc", "ps4", "xb1", "switch"], hours: 50,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "cosy"], starter: true, aka: ["dq11", "dqxi", "dragon quest 11"],
      pitch: "Pure, comforting classic JRPG: a chosen hero, a lovable party, and a world that keeps on giving." },
    { id: "dq3", title: "Dragon Quest III HD-2D Remake", year: 2024, series: "dragon-quest", platforms: ["pc", "ps5", "xsx", "switch"], hours: 30,
      tags: ["turn-based", "party", "jrpg", "fantasy", "retro", "builds"], aka: ["dq3", "dragon quest 3"],
      pitch: "A lavish remake of the classic: build your own party of classes and set out to save the world." },
    { id: "octopath2", title: "Octopath Traveler II", year: 2023, series: "octopath", platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 60,
      tags: ["turn-based", "party", "jrpg", "fantasy", "retro", "story", "builds"], aka: ["octopath 2"],
      pitch: "Eight travellers, eight stories, and a satisfying break-and-boost battle system in beautiful pixel art." },
    { id: "octopath1", title: "Octopath Traveler", year: 2018, series: "octopath", platforms: ["pc", "xb1", "switch"], hours: 60,
      tags: ["turn-based", "party", "jrpg", "fantasy", "retro", "builds"], aka: ["octopath"],
      pitch: "The original eight-hero anthology; looser storytelling than the sequel but the same excellent combat." },
    { id: "sea-of-stars", title: "Sea of Stars", year: 2023, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 28,
      tags: ["turn-based", "party", "jrpg", "fantasy", "retro", "cosy"], starter: true,
      pitch: "A gorgeous modern love letter to 16-bit RPGs, with timing-based turn-based combat." },
    { id: "chained-echoes", title: "Chained Echoes", year: 2022, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 30,
      tags: ["turn-based", "party", "jrpg", "fantasy", "retro", "story"],
      pitch: "A 16-bit-style epic with mechs, a war-torn continent, and a clever battle system that cuts out grinding." },
    { id: "chrono-trigger", title: "Chrono Trigger", year: 1995, series: "chrono", platforms: ["pc", "mobile", "snes"], hours: 23,
      tags: ["turn-based", "party", "jrpg", "fantasy", "retro", "story"], starter: true, aka: ["chrono"],
      pitch: "The time-travelling classic with many endings; still a near-perfect couple of weeks of play." },
    { id: "suikoden", title: "Suikoden I & II HD Remaster", year: 2025, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 45,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "retro"],
      pitch: "Recruit 108 stars of destiny across two classic war stories; the second is one of the genre's best." },
    { id: "eiyuden", title: "Eiyuden Chronicle: Hundred Heroes", year: 2024, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 45,
      tags: ["turn-based", "party", "jrpg", "fantasy", "retro", "cosy"],
      pitch: "A spiritual successor to Suikoden from its creator, with a hundred-plus recruitable heroes and castle building." },
    { id: "ys8", title: "Ys VIII: Lacrimosa of Dana", year: 2017, platforms: ["pc", "ps4", "switch"], hours: 35,
      tags: ["action", "party", "jrpg", "fantasy", "exploration"], aka: ["ys 8"],
      pitch: "Shipwrecked on a mysterious island, with fast, arcadey combat and very satisfying exploration." },
    { id: "nier-automata", title: "NieR:Automata", year: 2017, platforms: ["pc", "ps4", "xb1", "switch"], hours: 30,
      tags: ["action", "solo", "jrpg", "sci-fi", "story", "emotional", "surreal"], aka: ["nier", "automata"],
      pitch: "Androids fight machines on an abandoned Earth; keep playing past the first ending, because it is only the start." },
    { id: "yakuza-lad", title: "Yakuza: Like a Dragon", year: 2020, series: "like-a-dragon", platforms: ["pc", "ps5", "ps4", "xsx", "xb1"], hours: 45,
      tags: ["turn-based", "party", "jrpg", "modern", "humour", "story"], aka: ["yakuza", "like a dragon", "lad"],
      pitch: "A down-on-his-luck hero who imagines street fights as fantasy battles; hilarious and big-hearted." },
    { id: "infinite-wealth", title: "Like a Dragon: Infinite Wealth", year: 2024, series: "like-a-dragon", platforms: ["pc", "ps5", "ps4", "xsx", "xb1"], hours: 55,
      tags: ["turn-based", "party", "jrpg", "modern", "humour", "story", "emotional"], aka: ["yakuza", "like a dragon", "lad"],
      pitch: "The gang heads to Hawaii in a bigger, warmer sequel packed with absurd side activities." },
    { id: "tales-arise", title: "Tales of Arise", year: 2021, series: "tales", platforms: ["pc", "ps5", "ps4", "xsx", "xb1"], hours: 45,
      tags: ["action", "party", "jrpg", "fantasy", "story"], aka: ["tales"],
      pitch: "Flashy, combo-heavy action across two worlds, with a likeable cast fighting for liberation." },
    { id: "tales-vesperia", title: "Tales of Vesperia: Definitive Edition", year: 2019, series: "tales", platforms: ["pc", "ps4", "xb1", "switch"], hours: 50,
      tags: ["action", "party", "jrpg", "fantasy", "story", "humour"], aka: ["tales", "vesperia"],
      pitch: "A fan favourite led by a morally grey hero; a great way into the Tales series." },
    { id: "ni-no-kuni", title: "Ni no Kuni: Wrath of the White Witch Remastered", year: 2019, platforms: ["pc", "ps4", "switch"], hours: 40,
      tags: ["party", "jrpg", "fantasy", "cosy", "emotional"],
      pitch: "A storybook adventure animated by Studio Ghibli, about a boy trying to bring his mother back." },
    { id: "pokemon-arceus", title: "Pokémon Legends: Arceus", year: 2022, series: "pokemon", platforms: ["switch"], hours: 25,
      tags: ["turn-based", "solo", "jrpg", "open-world", "exploration", "cosy"], aka: ["pokemon", "arceus"],
      pitch: "A looser, exploration-first Pokémon where you catch creatures out in the wilds of a historical region." },
    { id: "ttyd", title: "Paper Mario: The Thousand-Year Door", year: 2024, series: "mario-rpg", platforms: ["switch"], hours: 30,
      tags: ["turn-based", "party", "humour", "cosy", "story"], starter: true, aka: ["paper mario", "mario"],
      pitch: "A remake of the beloved GameCube adventure: battles staged in front of an audience, and genuinely funny writing." },
    { id: "smrpg", title: "Super Mario RPG", year: 2023, series: "mario-rpg", platforms: ["switch"], hours: 12,
      tags: ["turn-based", "party", "humour", "cosy"], aka: ["mario"],
      pitch: "A short, breezy remake of the SNES classic; a perfect first RPG or a palate cleanser between big ones." },
    { id: "brothership", title: "Mario & Luigi: Brothership", year: 2024, series: "mario-rpg", platforms: ["switch"], hours: 40,
      tags: ["turn-based", "party", "humour", "cosy"], aka: ["mario", "luigi"],
      pitch: "An island-hopping adventure for the brothers, with timing-based battles and plenty of slapstick." },

    // Super Nintendo classics
    { id: "ff4-snes", title: "Final Fantasy IV", year: 1991, platforms: ["snes"], hours: 23,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "retro"], aka: ["ff4", "ffiv", "final fantasy 4", "final fantasy ii"],
      note: "Also remastered in the Final Fantasy Pixel Remaster collection.",
      pitch: "The one that introduced the active-time battle system, with a cast that keeps changing as the story goes." },
    { id: "ff6-snes", title: "Final Fantasy VI", year: 1994, platforms: ["snes"], hours: 35,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "retro", "emotional"], aka: ["ff6", "ffvi", "final fantasy 6", "final fantasy iii"],
      note: "Also on modern platforms as Final Fantasy VI Pixel Remaster.",
      pitch: "A huge ensemble cast, a world that ends halfway through, and one of gaming's great villains." },
    { id: "earthbound", title: "EarthBound", year: 1995, platforms: ["snes"], hours: 30,
      tags: ["turn-based", "party", "modern", "humour", "surreal", "story", "retro"], starter: true, aka: ["mother 2", "mother"],
      pitch: "Baseball bats, psychics, and a neighbourhood full of weirdness; funny and heartfelt until it gets quietly devastating." },
    { id: "secret-of-mana", title: "Secret of Mana", year: 1993, platforms: ["snes"], hours: 20,
      tags: ["action", "party", "fantasy", "exploration", "cosy", "retro"], aka: ["mana"],
      pitch: "Real-time swordplay and a famous soundtrack, built for playing through with a friend beside you." },
    { id: "smrpg-snes", title: "Super Mario RPG: Legend of the Seven Stars", year: 1996, series: "mario-rpg", platforms: ["snes"], hours: 17,
      tags: ["turn-based", "party", "humour", "cosy", "retro"], starter: true, aka: ["mario rpg", "mario"],
      note: "Remade for Switch in 2023.",
      pitch: "Squaresoft's Mario crossover: timed hits, isometric puzzles, and a very silly script that still lands." },
    { id: "terranigma", title: "Terranigma", year: 1995, platforms: ["snes"], hours: 25,
      tags: ["action", "solo", "fantasy", "story", "emotional", "exploration", "retro"],
      pitch: "A boy rebuilds the world piece by piece; an ambitious, melancholy action RPG that never officially reached America." },
    { id: "illusion-of-time", title: "Illusion of Time", year: 1995, platforms: ["snes"], hours: 20,
      tags: ["action", "solo", "fantasy", "story", "exploration", "retro"], aka: ["illusion of gaia"],
      pitch: "A globe-trotting adventure with psychic powers and dark turns; known as Illusion of Gaia in the States." },
    { id: "secret-of-evermore", title: "Secret of Evermore", year: 1995, platforms: ["snes"], hours: 23,
      tags: ["action", "solo", "fantasy", "sci-fi", "humour", "exploration", "retro"],
      pitch: "A boy and his dog tumble through a theme park's simulated worlds; an odd, atmospheric Mana cousin with alchemy instead of magic." },

    // Sega Mega Drive classics
    { id: "phantasy-star-2", title: "Phantasy Star II", year: 1989, series: "phantasy-star", platforms: ["megadrive"], hours: 30,
      tags: ["turn-based", "party", "jrpg", "sci-fi", "challenge", "story", "retro"], aka: ["phantasy star"],
      pitch: "A bleak, generation-spanning sci-fi epic with maze-like dungeons; the game that made Sega's name in RPGs." },
    { id: "phantasy-star-4", title: "Phantasy Star IV: The End of the Millennium", year: 1993, series: "phantasy-star", platforms: ["megadrive"], hours: 25,
      tags: ["turn-based", "party", "jrpg", "sci-fi", "story", "retro"], aka: ["phantasy star"],
      pitch: "The Algol saga's big finish: faster and friendlier than its predecessors, with comic-panel cutscenes and a proper conclusion." },
    { id: "shining-force-2", title: "Shining Force II", year: 1993, series: "shining", platforms: ["megadrive"], hours: 30,
      tags: ["tactics", "party", "jrpg", "fantasy", "builds", "retro"], aka: ["shining force"],
      pitch: "A grand tactical campaign with dozens of recruits and secret characters; the series at its most generous." },
    { id: "shining-darkness", title: "Shining in the Darkness", year: 1991, series: "shining", platforms: ["megadrive"], hours: 25,
      tags: ["turn-based", "party", "fantasy", "challenge", "retro"], aka: ["shining"],
      pitch: "A first-person dungeon crawl with trick walls and secret doors; the game that started the Shining series." },
    { id: "story-of-thor", title: "The Story of Thor", year: 1994, series: "story-of-thor", platforms: ["megadrive"], hours: 14,
      tags: ["action", "solo", "fantasy", "exploration", "retro"], aka: ["beyond oasis"],
      pitch: "Summon elemental spirits and brawl through dungeons in a colourful action RPG from the Streets of Rage team." },
    { id: "landstalker", title: "Landstalker: The Treasures of King Nole", year: 1992, platforms: ["megadrive"], hours: 21,
      tags: ["action", "solo", "fantasy", "exploration", "challenge", "retro"],
      pitch: "Isometric adventuring with leaps of faith and a treasure-hunting plot; charming enough to forgive the dodgy platforming." },
    { id: "light-crusader", title: "Light Crusader", year: 1995, platforms: ["megadrive"], hours: 10,
      tags: ["action", "solo", "fantasy", "exploration", "retro"],
      pitch: "Treasure's oddball isometric action RPG: swords, spells, and a castle full of genuinely clever puzzles." },

    // PlayStation 1 classics
    { id: "ff8", title: "Final Fantasy VIII", year: 1999, platforms: ["ps1", "pc", "ps4", "xb1", "switch"], hours: 42,
      tags: ["turn-based", "party", "jrpg", "modern", "story", "emotional", "retro"], aka: ["ff8", "ffviii", "final fantasy 8"],
      note: "On modern platforms it's the Remastered version.",
      pitch: "A military academy, a sorceress, and a love story; divisive on release, now fondly remembered for its ambition." },
    { id: "xenogears", title: "Xenogears", year: 1998, platforms: ["ps1"], hours: 60,
      tags: ["turn-based", "party", "jrpg", "sci-fi", "story", "emotional", "retro"], aka: ["xeno"],
      pitch: "Giant robots, reincarnation, and a plot that takes philosophy seriously; famously ambitious, and famously rushed at the end." },
    { id: "chrono-cross", title: "Chrono Cross", year: 1999, series: "chrono", platforms: ["ps1", "pc", "ps4", "xb1", "switch"], hours: 40,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "emotional", "retro"], aka: ["chrono"],
      note: "On modern platforms it's the Radical Dreamers Edition.",
      pitch: "Parallel worlds and a cast of dozens, with one of the finest soundtracks ever pressed to a disc." },
    { id: "vagrant-story", title: "Vagrant Story", year: 2000, platforms: ["ps1"], hours: 25,
      tags: ["action", "solo", "dark-fantasy", "story", "builds", "challenge", "retro"],
      pitch: "A dense, moody dungeon crawl through a ruined city, with weapon crafting and a story staged like a play." },
    { id: "grandia", title: "Grandia", year: 1999, platforms: ["ps1"], hours: 45,
      tags: ["turn-based", "party", "jrpg", "fantasy", "exploration", "story", "retro"],
      note: "Also remastered in the Grandia HD Collection on Switch.",
      pitch: "A proper adventure: a boy, a girl, a legend to chase, and one of the best turn-based battle systems of its era." },
    { id: "legend-of-dragoon", title: "The Legend of Dragoon", year: 1999, platforms: ["ps1"], hours: 40,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "retro"], aka: ["dragoon"],
      pitch: "Turn into a dragoon knight and time your combos in a lavish, four-disc epic that fans still campaign to revive." },

    // Sega Saturn classics
    { id: "panzer-dragoon-saga", title: "Panzer Dragoon Saga", year: 1998, platforms: ["saturn"], hours: 18,
      tags: ["action", "solo", "post-apoc", "story", "surreal", "retro"], aka: ["panzer dragoon"],
      pitch: "A haunting ride across a ruined world on a living dragon; only a few thousand copies ever reached Europe, and it's one of the era's best." },
    { id: "shining-force-3", title: "Shining Force III", year: 1997, series: "shining", platforms: ["saturn"], hours: 32,
      tags: ["tactics", "party", "jrpg", "fantasy", "story", "builds", "retro"], aka: ["shining force"],
      pitch: "A tactical war story told from three sides at once; the West only ever saw the first scenario." },
    { id: "shining-holy-ark", title: "Shining the Holy Ark", year: 1996, series: "shining", platforms: ["saturn"], hours: 30,
      tags: ["turn-based", "party", "fantasy", "challenge", "retro"], aka: ["shining"],
      pitch: "A first-person dungeon crawler with lovely pre-rendered corridors and a difficulty that keeps you mapping carefully." },
    { id: "dragon-force", title: "Dragon Force", year: 1996, platforms: ["saturn"], hours: 35,
      tags: ["tactics", "party", "fantasy", "builds", "retro"],
      pitch: "Command armies of up to a hundred soldiers in real-time clashes, then recruit the enemy generals you defeat." },
    { id: "magic-knight-rayearth", title: "Magic Knight Rayearth", year: 1995, platforms: ["saturn"], hours: 15,
      tags: ["action", "party", "fantasy", "story", "retro"],
      pitch: "An action RPG based on the magical-girl manga, with a warm script; also the last Saturn game released in America." },
    { id: "legend-of-oasis", title: "The Legend of Oasis", year: 1996, series: "story-of-thor", platforms: ["saturn"], hours: 12,
      tags: ["action", "solo", "fantasy", "exploration", "retro"], aka: ["story of thor 2", "beyond oasis 2"],
      pitch: "The Story of Thor's prequel: tighter, prettier, and packed with spirit-summoning combat." },

    // Nintendo 64 classics
    { id: "oot", title: "The Legend of Zelda: Ocarina of Time", year: 1998, series: "zelda", platforms: ["n64"], hours: 26,
      tags: ["action", "solo", "fantasy", "exploration", "story", "retro"], starter: true, aka: ["zelda", "ocarina"],
      pitch: "The one that showed the world what 3D adventure could be: time travel, secrets, and a Hyrule that still feels vast." },
    { id: "majoras-mask", title: "The Legend of Zelda: Majora's Mask", year: 2000, series: "zelda", platforms: ["n64"], hours: 20,
      tags: ["action", "solo", "fantasy", "exploration", "surreal", "emotional", "challenge", "retro"], aka: ["zelda", "majora"],
      pitch: "Three days until the moon falls; a stranger, sadder Zelda about masks, routines, and small human stories." },
    { id: "paper-mario-64", title: "Paper Mario", year: 2000, series: "mario-rpg", platforms: ["n64"], hours: 25,
      tags: ["turn-based", "party", "humour", "cosy", "story", "retro"], aka: ["mario", "paper mario"],
      pitch: "Mario's first paper caper, with timed-hit battles, a parade of oddball partners, and a very funny script." },
    { id: "ogre-battle-64", title: "Ogre Battle 64: Person of Lordly Caliber", year: 1999, platforms: ["n64"], hours: 48,
      tags: ["tactics", "party", "fantasy", "story", "builds", "retro"], aka: ["ogre battle"],
      pitch: "A stat-heavy tactics RPG about leading a revolution, with branching loyalties and unit management for days." }
  ]
};
