/*
 * The catalogue the recommender draws from.
 *
 * Each game has:
 *   id         unique slug, used in shareable links
 *   title      display name
 *   year       release year of this version
 *   series     optional; games in the same series get a small nudge together
 *   platforms  where this version is sold natively (see PLATFORMS below)
 *   hours      rough main-story length, in the spirit of HowLongToBeat's "Main Story" figure
 *   tags       taste tags (see TAGS below); these drive the matching
 *   pitch      one sentence shown on the results card
 *   aka        optional search aliases
 *   starter    optional; widely loved, approachable picks used when there is little to go on
 *   note       optional; shown under the platforms line
 *
 * Backward compatibility is handled in recommend.js, so a PS4 game only needs "ps4"
 * to show up for someone with a PS5, an Xbox One game shows up on Series X|S, and a
 * Switch game shows up on Switch 2.
 */
window.RPG_DATA = {
  updated: "October 2026",
  version: "1.0.0",

  platforms: [
    { key: "pc", label: "PC or Steam Deck", short: "PC" },
    { key: "ps5", label: "PlayStation 5", short: "PS5" },
    { key: "ps4", label: "PlayStation 4", short: "PS4" },
    { key: "xsx", label: "Xbox Series X|S", short: "Xbox Series" },
    { key: "xb1", label: "Xbox One", short: "Xbox One" },
    { key: "switch2", label: "Nintendo Switch 2", short: "Switch 2" },
    { key: "switch", label: "Nintendo Switch", short: "Switch" },
    { key: "mobile", label: "Phone or tablet", short: "Mobile" },
    { key: "snes", label: "Super Nintendo", short: "SNES" },
    { key: "megadrive", label: "Sega Mega Drive", short: "Mega Drive" },
    { key: "ps1", label: "PlayStation 1", short: "PS1" },
    { key: "saturn", label: "Sega Saturn", short: "Saturn" },
    { key: "n64", label: "Nintendo 64", short: "N64" },
    { key: "gamecube", label: "Nintendo GameCube", short: "GameCube" }
  ],

  // label: how the tag reads in a sentence; mood: offered as an "in the mood for" option
  tags: {
    "turn-based": { label: "turn-based battles", mood: "Turn-based battles", group: "play" },
    "action": { label: "real-time action combat", mood: "Real-time action", group: "play" },
    "tactics": { label: "grid-based tactics", mood: "Grid tactics", group: "play" },
    "rtwp": { label: "real-time-with-pause combat", mood: "Real-time with pause", group: "play" },
    "no-combat": { label: "little or no combat", mood: "Little or no combat", group: "play" },
    "open-world": { label: "an open world", mood: "Open world", group: "play" },
    "zelda-like": { label: "Zelda-like adventuring", mood: "Zelda-like", group: "play" },
    "builds": { label: "deep character builds", mood: "Deep character builds", group: "play" },
    "challenge": { label: "a tough challenge", mood: "A tough challenge", group: "play" },
    "loot": { label: "plenty of loot to chase", mood: "Loot hunting", group: "play" },
    "roguelite": { label: "roguelite runs" },
    "exploration": { label: "lots to explore" },
    "party": { label: "a party of companions" },
    "solo": { label: "a solo hero" },
    "jrpg": { label: "a JRPG style", mood: "JRPG style", group: "feel" },
    "crpg": { label: "classic PC RPG roots", mood: "Classic PC RPG style", group: "feel" },
    "story": { label: "a strong story", mood: "A strong story", group: "feel" },
    "choices": { label: "choices that matter", mood: "Choices that matter", group: "feel" },
    "social": { label: "friendships and daily life", mood: "Friendships and daily life", group: "feel" },
    "humour": { label: "a sense of humour", mood: "Something funny", group: "feel" },
    "cosy": { label: "a cosy feel", mood: "Something cosy", group: "feel" },
    "emotional": { label: "an emotional punch", mood: "Something moving", group: "feel" },
    "retro": { label: "a retro look", mood: "Retro pixel art", group: "feel" },
    "fantasy": { label: "a fantasy world" },
    "dark-fantasy": { label: "a dark fantasy world", mood: "Dark fantasy", group: "feel" },
    "sci-fi": { label: "a sci-fi setting", mood: "Sci-fi", group: "feel" },
    "post-apoc": { label: "a post-apocalyptic setting" },
    "modern": { label: "a modern-day setting" },
    "historical": { label: "a historical setting", mood: "Historical setting", group: "feel" },
    "surreal": { label: "a surreal streak" }
  },

  games: [
    // Open worlds and western action RPGs
    { id: "witcher3", title: "The Witcher 3: Wild Hunt", year: 2015, series: "witcher", platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 50,
      tags: ["action", "open-world", "solo", "dark-fantasy", "story", "choices", "exploration"], starter: true, aka: ["witcher"],
      pitch: "A monster hunter searches for his adopted daughter across a war-torn, beautifully written open world." },
    { id: "skyrim", title: "The Elder Scrolls V: Skyrim", year: 2011, series: "elder-scrolls", platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 34,
      tags: ["action", "open-world", "solo", "fantasy", "exploration", "builds"], starter: true, aka: ["tes", "elder scrolls"],
      pitch: "Pick a direction and start walking; the classic sandbox where your own detours become the story." },
    { id: "oblivion-r", title: "The Elder Scrolls IV: Oblivion Remastered", year: 2025, series: "elder-scrolls", platforms: ["pc", "ps5", "xsx"], hours: 28,
      tags: ["action", "open-world", "solo", "fantasy", "exploration", "builds", "humour"], aka: ["oblivion", "tes"],
      pitch: "A rebuilt take on the 2006 classic, with brilliant guild questlines and a gloriously odd sense of humour." },
    { id: "cyberpunk", title: "Cyberpunk 2077", year: 2020, platforms: ["pc", "ps5", "xsx", "switch2"], hours: 26,
      tags: ["action", "open-world", "solo", "sci-fi", "story", "builds", "exploration"], starter: true, aka: ["2077"],
      pitch: "A dense neon city and sharp character writing, long since rebuilt after its rocky launch; the Phantom Liberty expansion is worth it." },
    { id: "fnv", title: "Fallout: New Vegas", year: 2010, series: "fallout", platforms: ["pc", "xb1"], hours: 27,
      tags: ["action", "open-world", "solo", "post-apoc", "choices", "humour", "builds"], aka: ["new vegas", "fallout nv"], note: "Xbox via backward compatibility",
      pitch: "Many fans' favourite Fallout: faction politics, sharp writing, and choices with real consequences." },
    { id: "fallout4", title: "Fallout 4", year: 2015, series: "fallout", platforms: ["pc", "ps4", "xb1"], hours: 27,
      tags: ["action", "open-world", "solo", "post-apoc", "exploration", "loot", "builds"],
      pitch: "A huge ruined Boston to scavenge, with settlement building and satisfying gunplay." },
    { id: "outer-worlds", title: "The Outer Worlds", year: 2019, series: "outer-worlds", platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 14,
      tags: ["action", "party", "sci-fi", "humour", "choices", "story"],
      pitch: "A compact, satirical space romp from Obsidian; Fallout energy in a fraction of the hours." },
    { id: "starfield", title: "Starfield", year: 2023, platforms: ["pc", "xsx"], hours: 23,
      tags: ["action", "open-world", "solo", "sci-fi", "exploration", "builds"],
      pitch: "Bethesda's space sandbox: build ships, join factions, and land on more planets than you will ever finish." },
    { id: "avowed", title: "Avowed", year: 2025, platforms: ["pc", "xsx"], hours: 25,
      tags: ["action", "solo", "fantasy", "story", "choices", "exploration"],
      pitch: "Obsidian's first-person fantasy set in the Pillars of Eternity world, with lively spell-and-sword combat." },
    { id: "kcd", title: "Kingdom Come: Deliverance", year: 2018, series: "kcd", platforms: ["pc", "ps4", "xb1", "switch"], hours: 42,
      tags: ["action", "open-world", "solo", "historical", "challenge", "story"], aka: ["kcd"],
      pitch: "Medieval Bohemia with no magic and no dragons, where you start out genuinely bad at everything." },
    { id: "kcd2", title: "Kingdom Come: Deliverance II", year: 2025, series: "kcd", platforms: ["pc", "ps5", "xsx"], hours: 55,
      tags: ["action", "open-world", "solo", "historical", "story", "challenge", "humour", "exploration"], aka: ["kcd2", "kcd 2"],
      pitch: "A bigger, funnier, more confident sequel and one of the most immersive historical worlds in games." },
    { id: "dd2", title: "Dragon's Dogma 2", year: 2024, series: "dragons-dogma", platforms: ["pc", "ps5", "xsx"], hours: 30,
      tags: ["action", "open-world", "party", "fantasy", "exploration", "builds"],
      pitch: "Clamber up giant monsters with a party of AI companions and let the open world surprise you." },
    { id: "dd1", title: "Dragon's Dogma: Dark Arisen", year: 2016, series: "dragons-dogma", platforms: ["pc", "ps4", "xb1", "switch"], hours: 35,
      tags: ["action", "open-world", "party", "fantasy", "exploration", "builds"],
      pitch: "The cult original: the same monster climbing and helper companions in a scrappier package." },
    { id: "hogwarts", title: "Hogwarts Legacy", year: 2023, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch2", "switch"], hours: 26,
      tags: ["action", "open-world", "solo", "fantasy", "exploration", "cosy"],
      pitch: "Wander a lovingly detailed wizarding school and the countryside around it at your own pace." },
    { id: "horizon-zd", title: "Horizon Zero Dawn", year: 2017, series: "horizon", platforms: ["pc", "ps5", "ps4"], hours: 22,
      tags: ["action", "open-world", "solo", "sci-fi", "exploration", "story"],
      pitch: "Hunt robotic beasts across a lush post-apocalyptic wilderness, with a central mystery that pays off." },
    { id: "amalur", title: "Kingdoms of Amalur: Re-Reckoning", year: 2020, platforms: ["pc", "ps4", "xb1", "switch"], hours: 40,
      tags: ["action", "open-world", "solo", "fantasy", "loot", "builds", "exploration"], aka: ["amalur"],
      pitch: "Big, colourful fantasy with punchy combat and a flexible class system; proper comfort food." },
    { id: "vtmb", title: "Vampire: The Masquerade - Bloodlines", year: 2004, platforms: ["pc"], hours: 30,
      tags: ["action", "solo", "modern", "dark-fantasy", "story", "choices", "humour"], aka: ["bloodlines", "vtmb"],
      pitch: "A janky but beloved cult classic about vampire politics in night-time Los Angeles, with superb writing." },

    // Soulslikes and action RPGs
    { id: "elden-ring", title: "Elden Ring", year: 2022, series: "souls", platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch2"], hours: 60,
      tags: ["action", "open-world", "solo", "dark-fantasy", "challenge", "exploration", "builds"], starter: true,
      pitch: "FromSoftware's open-world epic: brutal bosses, a vast mysterious map, and total freedom over where to go next." },
    { id: "ds-r", title: "Dark Souls Remastered", year: 2018, series: "souls", platforms: ["pc", "ps4", "xb1", "switch"], hours: 42,
      tags: ["action", "solo", "dark-fantasy", "challenge", "exploration", "builds"], aka: ["dark souls 1"],
      pitch: "The unforgiving original that defined a genre, with an interlocking world where every shortcut feels earned." },
    { id: "ds3", title: "Dark Souls III", year: 2016, series: "souls", platforms: ["pc", "ps4", "xb1"], hours: 32,
      tags: ["action", "solo", "dark-fantasy", "challenge", "builds"], aka: ["ds3"],
      pitch: "Faster and more aggressive than its predecessors, with some of the best boss fights FromSoftware has made." },
    { id: "bloodborne", title: "Bloodborne", year: 2015, series: "souls", platforms: ["ps4"], hours: 33,
      tags: ["action", "solo", "dark-fantasy", "challenge", "exploration"],
      pitch: "Gothic horror with a fast combat style that rewards you for attacking rather than hiding behind a shield." },
    { id: "demons-souls", title: "Demon's Souls", year: 2020, series: "souls", platforms: ["ps5"], hours: 25,
      tags: ["action", "solo", "dark-fantasy", "challenge"],
      pitch: "A gorgeous remake of the game that started it all; compact, tense, and a showcase for the PS5." },
    { id: "lies-of-p", title: "Lies of P", year: 2023, platforms: ["pc", "ps5", "ps4", "xsx", "xb1"], hours: 30,
      tags: ["action", "solo", "dark-fantasy", "challenge", "builds"],
      pitch: "A dark Pinocchio retelling with tight, parry-focused combat; one of the best soulslikes not made by FromSoftware." },
    { id: "nioh2", title: "Nioh 2", year: 2020, platforms: ["pc", "ps5", "ps4"], hours: 50,
      tags: ["action", "solo", "dark-fantasy", "historical", "challenge", "builds", "loot"],
      pitch: "A samurai soulslike with layered combat stances and a deep loot game for build tinkerers." },
    { id: "diablo4", title: "Diablo IV", year: 2023, platforms: ["pc", "ps5", "ps4", "xsx", "xb1"], hours: 25,
      tags: ["action", "solo", "dark-fantasy", "loot", "builds"], aka: ["diablo 4"],
      pitch: "Slick, gothic loot chasing with a surprisingly strong campaign, and an endless endgame if you want one." },
    { id: "grim-dawn", title: "Grim Dawn", year: 2016, platforms: ["pc", "xb1"], hours: 45,
      tags: ["action", "solo", "dark-fantasy", "loot", "builds", "challenge"],
      pitch: "A deep, old-school action RPG for theorycrafters, with dual classes and an enormous item pool." },
    { id: "torchlight2", title: "Torchlight II", year: 2012, platforms: ["pc", "ps4", "xb1", "switch"], hours: 20,
      tags: ["action", "solo", "fantasy", "loot", "builds", "cosy"],
      pitch: "Bright, approachable loot chasing; Diablo with the edges sanded off." },
    { id: "hades", title: "Hades", year: 2020, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 22,
      tags: ["action", "solo", "roguelite", "fantasy", "story", "challenge", "builds"],
      pitch: "Fight your way out of the underworld again and again; every run moves the story and your power forward." },

    // Party-based western RPGs
    { id: "bg3", title: "Baldur's Gate 3", year: 2023, series: "baldurs-gate", platforms: ["pc", "ps5", "xsx"], hours: 70,
      tags: ["turn-based", "party", "crpg", "fantasy", "story", "choices", "builds", "humour"], starter: true, aka: ["bg3", "baldurs gate"],
      pitch: "Dungeons & Dragons brought to life: a sprawling party adventure where nearly any plan you come up with actually works." },
    { id: "bg2", title: "Baldur's Gate II: Enhanced Edition", year: 2013, series: "baldurs-gate", platforms: ["pc", "ps4", "xb1", "switch", "mobile"], hours: 60,
      tags: ["rtwp", "party", "crpg", "fantasy", "story", "builds", "retro"], aka: ["bg2"],
      pitch: "The real-time-with-pause epic, with a legendary villain and companions people still talk about decades later." },
    { id: "dos2", title: "Divinity: Original Sin 2", year: 2017, platforms: ["pc", "ps4", "xb1", "switch"], hours: 60,
      tags: ["turn-based", "party", "crpg", "fantasy", "choices", "builds", "humour", "challenge"], aka: ["dos2", "divinity"],
      pitch: "Larian's systemic playground before Baldur's Gate 3, built on elemental combos and co-op chaos." },
    { id: "pillars", title: "Pillars of Eternity", year: 2015, series: "pillars", platforms: ["pc", "ps4", "xb1", "switch"], hours: 37,
      tags: ["rtwp", "party", "crpg", "fantasy", "story", "builds"], aka: ["poe"],
      pitch: "A love letter to the Infinity Engine classics, with thoughtful writing about souls and faith." },
    { id: "deadfire", title: "Pillars of Eternity II: Deadfire", year: 2018, series: "pillars", platforms: ["pc", "ps4", "xb1", "switch"], hours: 45,
      tags: ["rtwp", "party", "crpg", "fantasy", "exploration", "builds", "choices"], aka: ["poe2", "deadfire"],
      pitch: "Pirate-flavoured island hopping with ship battles, rival factions, and an optional turn-based mode." },
    { id: "wotr", title: "Pathfinder: Wrath of the Righteous", year: 2021, platforms: ["pc", "ps4", "xb1"], hours: 75,
      tags: ["rtwp", "turn-based", "party", "crpg", "fantasy", "builds", "choices", "challenge"], aka: ["pathfinder", "wotr"],
      pitch: "A crusade against demons with absurdly deep character building and mythic paths that reshape your story." },
    { id: "rogue-trader", title: "Warhammer 40,000: Rogue Trader", year: 2023, platforms: ["pc", "ps5", "xsx"], hours: 70,
      tags: ["turn-based", "party", "crpg", "sci-fi", "choices", "builds", "story"], aka: ["40k", "rogue trader"],
      pitch: "Run a starship dynasty in the grim far future, with tactical turn-based fights and weighty choices." },
    { id: "wasteland3", title: "Wasteland 3", year: 2020, platforms: ["pc", "ps4", "xb1"], hours: 40,
      tags: ["turn-based", "party", "crpg", "post-apoc", "choices", "humour", "builds"],
      pitch: "Squad-based survival in a frozen, post-apocalyptic Colorado, with dark humour and tough moral calls." },
    { id: "shadowrun-df", title: "Shadowrun: Dragonfall", year: 2014, platforms: ["pc", "ps4", "xb1", "switch"], hours: 25,
      tags: ["turn-based", "party", "crpg", "sci-fi", "story", "choices"], aka: ["shadowrun"], note: "On consoles it comes in the Shadowrun Trilogy",
      pitch: "Cyberpunk meets fantasy in a near-future Berlin, with turn-based tactics and some of the best writing in the genre." },
    { id: "pst", title: "Planescape: Torment Enhanced Edition", year: 2017, platforms: ["pc", "ps4", "xb1", "switch", "mobile"], hours: 30,
      tags: ["rtwp", "party", "crpg", "surreal", "story", "choices", "retro"], aka: ["planescape"],
      pitch: "A philosophical classic about an amnesiac immortal; best for patient players who love to read." },
    { id: "tyranny", title: "Tyranny", year: 2016, platforms: ["pc"], hours: 22,
      tags: ["rtwp", "party", "crpg", "dark-fantasy", "choices", "story"],
      pitch: "Evil has already won and you work for it; a short, reactive story with big branching paths." },
    { id: "mass-effect", title: "Mass Effect Legendary Edition", year: 2021, series: "mass-effect", platforms: ["pc", "ps4", "xb1"], hours: 65,
      tags: ["action", "party", "sci-fi", "story", "choices", "emotional"], starter: true, aka: ["mass effect", "me1", "me2", "me3"],
      pitch: "The full trilogy: build a crew, make hard calls, and watch them echo across three games." },
    { id: "kotor", title: "Star Wars: Knights of the Old Republic", year: 2003, platforms: ["pc", "switch", "mobile"], hours: 30,
      tags: ["rtwp", "party", "sci-fi", "story", "choices", "retro"], aka: ["kotor", "star wars"],
      pitch: "BioWare's classic set thousands of years before the films, with a plot twist that is still talked about." },
    { id: "dao", title: "Dragon Age: Origins", year: 2009, series: "dragon-age", platforms: ["pc", "xb1"], hours: 40,
      tags: ["rtwp", "party", "dark-fantasy", "story", "choices", "builds"], aka: ["dao"], note: "Xbox via backward compatibility",
      pitch: "Gritty fantasy with tactical party combat and companions who will absolutely judge your choices." },
    { id: "dai", title: "Dragon Age: Inquisition", year: 2014, series: "dragon-age", platforms: ["pc", "ps4", "xb1"], hours: 47,
      tags: ["action", "party", "fantasy", "story", "choices", "exploration"], aka: ["dai"],
      pitch: "Lead a growing order across large open zones, backed by a great cast of companions." },
    { id: "veilguard", title: "Dragon Age: The Veilguard", year: 2024, series: "dragon-age", platforms: ["pc", "ps5", "xsx"], hours: 45,
      tags: ["action", "party", "fantasy", "story"],
      pitch: "A brighter, faster, more action-led Dragon Age built around a close-knit crew." },
    { id: "darkest-dungeon", title: "Darkest Dungeon", year: 2016, platforms: ["pc", "ps4", "xb1", "switch"], hours: 45,
      tags: ["turn-based", "party", "dark-fantasy", "challenge", "roguelite", "builds"],
      pitch: "Lead a doomed roster into gothic dungeons, where stress can break your heroes as surely as monsters can." },

    // Narrative-first and short
    { id: "disco", title: "Disco Elysium: The Final Cut", year: 2021, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 22,
      tags: ["no-combat", "crpg", "solo", "surreal", "story", "choices", "humour"], starter: true, aka: ["disco elysium"],
      pitch: "A detective RPG with no combat at all, where the arguing voices in your own head are the party." },
    { id: "pentiment", title: "Pentiment", year: 2022, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 18,
      tags: ["no-combat", "solo", "historical", "story", "choices"],
      pitch: "A murder mystery in a 16th-century Bavarian village, illustrated like a living manuscript." },
    { id: "citizen-sleeper", title: "Citizen Sleeper", year: 2022, series: "citizen-sleeper", platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 8,
      tags: ["no-combat", "solo", "sci-fi", "story", "choices", "emotional"],
      pitch: "Dice-driven survival on a decaying space station; a short story about precarity, kindness, and making a life." },
    { id: "citizen-sleeper-2", title: "Citizen Sleeper 2: Starward Vector", year: 2025, series: "citizen-sleeper", platforms: ["pc", "ps5", "xsx", "switch"], hours: 14,
      tags: ["no-combat", "party", "sci-fi", "story", "choices", "emotional"],
      pitch: "A bigger, tenser sequel: gather a crew and keep everyone alive on the run between stations." },
    { id: "undertale", title: "Undertale", year: 2015, platforms: ["pc", "ps4", "xb1", "switch"], hours: 6,
      tags: ["turn-based", "solo", "surreal", "humour", "emotional", "retro"], starter: true,
      pitch: "A short, heartfelt cult hit where you can befriend every monster instead of fighting them." },
    { id: "deltarune", title: "Deltarune", year: 2025, platforms: ["pc", "ps5", "ps4", "switch2", "switch"], hours: 15,
      tags: ["turn-based", "party", "surreal", "humour", "emotional", "retro"], note: "Chapters 1 to 4 so far; more on the way",
      pitch: "The follow-up to Undertale, released in chapters; funnier, stranger, and with a proper party." },
    { id: "omori", title: "OMORI", year: 2020, platforms: ["pc", "ps4", "xb1", "switch"], hours: 20,
      tags: ["turn-based", "party", "surreal", "emotional", "story", "retro"],
      pitch: "A cheerful-looking adventure that slowly becomes an unsettling story about guilt and grief; it deals with heavy themes." },

    // JRPGs
    { id: "clair-obscur", title: "Clair Obscur: Expedition 33", year: 2025, platforms: ["pc", "ps5", "xsx"], hours: 32,
      tags: ["turn-based", "party", "jrpg", "fantasy", "surreal", "story", "emotional", "challenge"], starter: true, aka: ["e33", "expedition 33"],
      pitch: "Belle Époque-inspired fantasy whose turn-based fights you dodge and parry in real time; a standout of 2025." },
    { id: "p5r", title: "Persona 5 Royal", year: 2020, series: "persona", platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 100,
      tags: ["turn-based", "party", "jrpg", "modern", "social", "story"], starter: true, aka: ["p5r", "persona 5", "p5"],
      pitch: "Stylish phantom thieves in modern Tokyo: dungeon crawling by night, school life and friendships by day." },
    { id: "p4g", title: "Persona 4 Golden", year: 2012, series: "persona", platforms: ["pc", "ps4", "xb1", "switch"], hours: 55,
      tags: ["turn-based", "party", "jrpg", "modern", "social", "story", "humour"], aka: ["p4g", "persona 4", "p4"],
      pitch: "A small-town murder mystery with one of the warmest casts in any JRPG." },
    { id: "p3r", title: "Persona 3 Reload", year: 2024, series: "persona", platforms: ["pc", "ps5", "ps4", "xsx", "xb1"], hours: 60,
      tags: ["turn-based", "party", "jrpg", "modern", "social", "story", "emotional"], aka: ["p3r", "persona 3", "p3"],
      pitch: "A full remake of the Dark Hour classic; moodier than Persona 5 and quietly devastating." },
    { id: "metaphor", title: "Metaphor: ReFantazio", year: 2024, platforms: ["pc", "ps5", "ps4", "xsx"], hours: 75,
      tags: ["turn-based", "party", "jrpg", "fantasy", "social", "story"], aka: ["refantazio"],
      pitch: "Atlus's fantasy election epic, with a Persona-style calendar and bonds wrapped around a political journey." },
    { id: "smt5v", title: "Shin Megami Tensei V: Vengeance", year: 2024, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 55,
      tags: ["turn-based", "party", "jrpg", "post-apoc", "challenge", "builds"], aka: ["smt", "smt5", "smt v"],
      pitch: "Recruit and fuse demons in punishing battles where exploiting weaknesses is everything." },
    { id: "ff7r", title: "Final Fantasy VII Remake Intergrade", year: 2021, series: "ff7-remake", platforms: ["pc", "ps5", "xsx", "switch2"], hours: 34,
      tags: ["action", "party", "jrpg", "sci-fi", "story"], starter: true, aka: ["ff7", "ffvii", "ff7 remake", "final fantasy 7"],
      pitch: "The first part of the remake trilogy, expanding Midgar into a full game with hybrid action and command combat." },
    { id: "ff7rb", title: "Final Fantasy VII Rebirth", year: 2024, series: "ff7-remake", platforms: ["pc", "ps5"], hours: 45,
      tags: ["action", "party", "jrpg", "open-world", "fantasy", "story", "exploration"], aka: ["ff7", "ffvii", "rebirth", "final fantasy 7"],
      pitch: "The trilogy's second part opens up into huge regions full of side content, minigames, and party banter." },
    { id: "ff7", title: "Final Fantasy VII", year: 1997, platforms: ["pc", "ps4", "xb1", "switch", "mobile", "ps1"], hours: 37,
      tags: ["turn-based", "party", "jrpg", "sci-fi", "story", "retro"], aka: ["ff7", "ffvii", "final fantasy 7", "original"],
      pitch: "The 1997 original, still compelling for its materia system and its story about a planet being drained dry." },
    { id: "ff6", title: "Final Fantasy VI Pixel Remaster", year: 2022, platforms: ["pc", "ps4", "xsx", "switch", "mobile"], hours: 35,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "retro", "emotional"], aka: ["ff6", "ffvi", "final fantasy 6"],
      pitch: "Often called the series' peak, with a huge ensemble cast and a world that changes dramatically halfway through." },
    { id: "ff9", title: "Final Fantasy IX", year: 2000, platforms: ["pc", "ps4", "xb1", "switch", "mobile", "ps1"], hours: 40,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "emotional", "retro"], aka: ["ff9", "ffix", "final fantasy 9"],
      pitch: "A warm, storybook return to classic fantasy, with a cast that grows on you and a lot to say about mortality." },
    { id: "ffx", title: "Final Fantasy X HD Remaster", year: 2014, platforms: ["pc", "ps4", "xb1", "switch"], hours: 45,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "emotional"], aka: ["ffx", "ff10", "final fantasy 10"], note: "Sold with X-2 as a bundle",
      pitch: "A pilgrimage across a tropical world, with one of the cleanest turn-based battle systems in the series." },
    { id: "ff12", title: "Final Fantasy XII: The Zodiac Age", year: 2017, platforms: ["pc", "ps4", "xb1", "switch"], hours: 50,
      tags: ["rtwp", "party", "jrpg", "fantasy", "story", "builds", "exploration"], aka: ["ff12", "ffxii", "final fantasy 12"],
      pitch: "Political fantasy in Ivalice, with a gambit system that lets you script exactly how your party fights." },
    { id: "ff15", title: "Final Fantasy XV", year: 2016, platforms: ["pc", "ps4", "xb1"], hours: 28,
      tags: ["action", "party", "jrpg", "open-world", "fantasy", "story"], aka: ["ff15", "ffxv", "final fantasy 15"],
      pitch: "A road trip with four friends across an open world, with fast, warp-striking action combat." },
    { id: "ff16", title: "Final Fantasy XVI", year: 2023, platforms: ["pc", "ps5"], hours: 37,
      tags: ["action", "solo", "dark-fantasy", "story"], aka: ["ff16", "ffxvi", "final fantasy 16"],
      pitch: "A darker, more grown-up Final Fantasy with spectacular action combat and kaiju-sized summon battles." },
    { id: "fft", title: "Final Fantasy Tactics: The Ivalice Chronicles", year: 2025, platforms: ["pc", "ps5", "ps4", "xsx", "switch2", "switch"], hours: 45,
      tags: ["tactics", "party", "jrpg", "fantasy", "story", "builds", "challenge"], aka: ["fft", "final fantasy tactics"],
      pitch: "A rebuilt version of the 1997 tactics classic, with full voice acting and a famously flexible job system." },
    { id: "tactics-ogre", title: "Tactics Ogre: Reborn", year: 2022, platforms: ["pc", "ps5", "ps4", "switch"], hours: 40,
      tags: ["tactics", "party", "jrpg", "fantasy", "choices", "story", "challenge"],
      pitch: "A grounded war story where your decisions fracture the plot, from the team behind Final Fantasy Tactics." },
    { id: "unicorn-overlord", title: "Unicorn Overlord", year: 2024, platforms: ["ps5", "ps4", "xsx", "switch"], hours: 50,
      tags: ["tactics", "party", "jrpg", "fantasy", "builds"],
      pitch: "Vanillaware's army-building strategy RPG: set up squads, write their battle rules, then watch them play out." },
    { id: "fe3h", title: "Fire Emblem: Three Houses", year: 2019, series: "fire-emblem", platforms: ["switch"], hours: 50,
      tags: ["tactics", "party", "jrpg", "fantasy", "social", "story", "choices"], starter: true, aka: ["three houses", "fire emblem"],
      pitch: "Teach a class at a monastery, then lead them into war; the house you choose changes everything." },
    { id: "fe-engage", title: "Fire Emblem Engage", year: 2023, series: "fire-emblem", platforms: ["switch"], hours: 45,
      tags: ["tactics", "party", "jrpg", "fantasy", "challenge"], aka: ["fire emblem"],
      pitch: "The series' best pure combat, with flashy summons of past heroes; the story is lighter." },
    { id: "triangle", title: "Triangle Strategy", year: 2022, platforms: ["pc", "switch"], hours: 40,
      tags: ["tactics", "party", "jrpg", "fantasy", "choices", "story", "retro"],
      pitch: "Pixel-art tactics where your party votes on big decisions and you have to win them round." },
    { id: "live-a-live", title: "Live A Live", year: 2022, platforms: ["pc", "ps5", "ps4", "switch"], hours: 25,
      tags: ["tactics", "party", "jrpg", "retro", "story"],
      pitch: "Short, self-contained chapters set across wildly different eras, from prehistory to the far future." },
    { id: "xc1", title: "Xenoblade Chronicles: Definitive Edition", year: 2020, series: "xenoblade", platforms: ["switch"], hours: 60,
      tags: ["action", "party", "jrpg", "open-world", "fantasy", "exploration", "story"], aka: ["xenoblade"],
      pitch: "Explore landscapes on the bodies of two titanic, long-dead gods, with a fantastic soundtrack along the way." },
    { id: "xc2", title: "Xenoblade Chronicles 2", year: 2017, series: "xenoblade", platforms: ["switch"], hours: 70,
      tags: ["action", "party", "jrpg", "fantasy", "exploration", "story", "builds"], aka: ["xenoblade"],
      pitch: "A sea of clouds and nations on the backs of titans, with a slow-burning combat system that thrills once it clicks." },
    { id: "xc3", title: "Xenoblade Chronicles 3", year: 2022, series: "xenoblade", platforms: ["switch"], hours: 65,
      tags: ["action", "party", "jrpg", "fantasy", "story", "emotional", "exploration"], aka: ["xenoblade"],
      pitch: "Soldiers born to fight for ten years start to wonder whether life could be more; the series' most moving entry." },
    { id: "xcx", title: "Xenoblade Chronicles X: Definitive Edition", year: 2025, series: "xenoblade", platforms: ["switch"], hours: 70,
      tags: ["action", "party", "jrpg", "sci-fi", "open-world", "exploration", "builds"], aka: ["xenoblade x"],
      pitch: "Humanity crash-lands on an alien planet; vast exploration on foot, and later in giant mechs." },
    { id: "dq11", title: "Dragon Quest XI S: Echoes of an Elusive Age", year: 2019, series: "dragon-quest", platforms: ["pc", "ps4", "xb1", "switch"], hours: 50,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "cosy"], starter: true, aka: ["dq11", "dqxi", "dragon quest 11"],
      pitch: "Pure, comforting classic JRPG: a chosen hero, a lovable party, and a world that keeps on giving." },
    { id: "dq3", title: "Dragon Quest III HD-2D Remake", year: 2024, series: "dragon-quest", platforms: ["pc", "ps5", "xsx", "switch"], hours: 30,
      tags: ["turn-based", "party", "jrpg", "fantasy", "retro", "builds"], aka: ["dq3", "dragon quest 3"],
      pitch: "A lavish remake of the classic: build your own party of classes and set out to save the world." },
    { id: "octopath2", title: "Octopath Traveler II", year: 2023, series: "octopath", platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 60,
      tags: ["turn-based", "party", "jrpg", "fantasy", "retro", "story", "builds"], aka: ["octopath 2"],
      pitch: "Eight travellers, eight stories, and a satisfying break-and-boost battle system in beautiful pixel art." },
    { id: "octopath1", title: "Octopath Traveler", year: 2018, series: "octopath", platforms: ["pc", "xb1", "switch"], hours: 60,
      tags: ["turn-based", "party", "jrpg", "fantasy", "retro", "builds"], aka: ["octopath"],
      pitch: "The original eight-hero anthology; looser storytelling than the sequel but the same excellent combat." },
    { id: "sea-of-stars", title: "Sea of Stars", year: 2023, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 28,
      tags: ["turn-based", "party", "jrpg", "fantasy", "retro", "cosy"], starter: true,
      pitch: "A gorgeous modern love letter to 16-bit RPGs, with timing-based turn-based combat." },
    { id: "chained-echoes", title: "Chained Echoes", year: 2022, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 30,
      tags: ["turn-based", "party", "jrpg", "fantasy", "retro", "story"],
      pitch: "A 16-bit-style epic with mechs, a war-torn continent, and a clever battle system that cuts out grinding." },
    { id: "chrono-trigger", title: "Chrono Trigger", year: 1995, series: "chrono", platforms: ["pc", "mobile", "snes"], hours: 23,
      tags: ["turn-based", "party", "jrpg", "fantasy", "retro", "story"], starter: true, aka: ["chrono"],
      pitch: "The time-travelling classic with many endings; still a near-perfect couple of weeks of play." },
    { id: "suikoden", title: "Suikoden I & II HD Remaster", year: 2025, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 45,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "retro"],
      pitch: "Recruit 108 stars of destiny across two classic war stories; the second is one of the genre's best." },
    { id: "eiyuden", title: "Eiyuden Chronicle: Hundred Heroes", year: 2024, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 45,
      tags: ["turn-based", "party", "jrpg", "fantasy", "retro", "cosy"],
      pitch: "A spiritual successor to Suikoden from its creator, with a hundred-plus recruitable heroes and castle building." },
    { id: "ys8", title: "Ys VIII: Lacrimosa of Dana", year: 2017, series: "ys", platforms: ["pc", "ps4", "switch"], hours: 35,
      tags: ["action", "party", "jrpg", "fantasy", "exploration"], aka: ["ys 8"],
      pitch: "Shipwrecked on a mysterious island, with fast, arcadey combat and very satisfying exploration." },
    { id: "nier-automata", title: "NieR:Automata", year: 2017, platforms: ["pc", "ps4", "xb1", "switch"], hours: 30,
      tags: ["action", "solo", "jrpg", "sci-fi", "story", "emotional", "surreal"], aka: ["nier", "automata"],
      pitch: "Androids fight machines on an abandoned Earth; keep playing past the first ending, because it is only the start." },
    { id: "yakuza-lad", title: "Yakuza: Like a Dragon", year: 2020, series: "like-a-dragon", platforms: ["pc", "ps5", "ps4", "xsx", "xb1"], hours: 45,
      tags: ["turn-based", "party", "jrpg", "modern", "humour", "story"], aka: ["yakuza", "like a dragon", "lad"],
      pitch: "A down-on-his-luck hero who imagines street fights as fantasy battles; hilarious and big-hearted." },
    { id: "infinite-wealth", title: "Like a Dragon: Infinite Wealth", year: 2024, series: "like-a-dragon", platforms: ["pc", "ps5", "ps4", "xsx", "xb1"], hours: 55,
      tags: ["turn-based", "party", "jrpg", "modern", "humour", "story", "emotional"], aka: ["yakuza", "like a dragon", "lad"],
      pitch: "The gang heads to Hawaii in a bigger, warmer sequel packed with absurd side activities." },
    { id: "tales-arise", title: "Tales of Arise", year: 2021, series: "tales", platforms: ["pc", "ps5", "ps4", "xsx", "xb1"], hours: 45,
      tags: ["action", "party", "jrpg", "fantasy", "story"], aka: ["tales"],
      pitch: "Flashy, combo-heavy action across two worlds, with a likeable cast fighting for liberation." },
    { id: "tales-vesperia", title: "Tales of Vesperia: Definitive Edition", year: 2019, series: "tales", platforms: ["pc", "ps4", "xb1", "switch"], hours: 50,
      tags: ["action", "party", "jrpg", "fantasy", "story", "humour"], aka: ["tales", "vesperia"],
      pitch: "A fan favourite led by a morally grey hero; a great way into the Tales series." },
    { id: "ni-no-kuni", title: "Ni no Kuni: Wrath of the White Witch Remastered", year: 2019, platforms: ["pc", "ps4", "switch"], hours: 40,
      tags: ["party", "jrpg", "fantasy", "cosy", "emotional"],
      pitch: "A storybook adventure animated by Studio Ghibli, about a boy trying to bring his mother back." },
    { id: "pokemon-arceus", title: "Pokémon Legends: Arceus", year: 2022, series: "pokemon", platforms: ["switch"], hours: 25,
      tags: ["turn-based", "solo", "jrpg", "open-world", "exploration", "cosy"], aka: ["pokemon", "arceus"],
      pitch: "A looser, exploration-first Pokémon where you catch creatures out in the wilds of a historical region." },
    { id: "ttyd", title: "Paper Mario: The Thousand-Year Door", year: 2024, series: "mario-rpg", platforms: ["switch"], hours: 30,
      tags: ["turn-based", "party", "humour", "cosy", "story"], starter: true, aka: ["paper mario", "mario"],
      pitch: "A remake of the beloved GameCube adventure: battles staged in front of an audience, and genuinely funny writing." },
    { id: "smrpg", title: "Super Mario RPG", year: 2023, series: "mario-rpg", platforms: ["switch"], hours: 12,
      tags: ["turn-based", "party", "humour", "cosy"], aka: ["mario"],
      pitch: "A short, breezy remake of the SNES classic; a perfect first RPG or a palate cleanser between big ones." },
    { id: "brothership", title: "Mario & Luigi: Brothership", year: 2024, series: "mario-rpg", platforms: ["switch"], hours: 40,
      tags: ["turn-based", "party", "humour", "cosy"], aka: ["mario", "luigi"],
      pitch: "An island-hopping adventure for the brothers, with timing-based battles and plenty of slapstick." },

    // Super Nintendo classics
    { id: "ff4-snes", title: "Final Fantasy IV", year: 1991, platforms: ["snes"], hours: 23,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "retro"], aka: ["ff4", "ffiv", "final fantasy 4", "final fantasy ii"],
      note: "Also remastered in the Final Fantasy Pixel Remaster collection.",
      pitch: "The one that introduced the active-time battle system, with a cast that keeps changing as the story goes." },
    { id: "ff6-snes", title: "Final Fantasy VI", year: 1994, platforms: ["snes"], hours: 35,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "retro", "emotional"], aka: ["ff6", "ffvi", "final fantasy 6", "final fantasy iii"],
      note: "Also on modern platforms as Final Fantasy VI Pixel Remaster.",
      pitch: "A huge ensemble cast, a world that ends halfway through, and one of gaming's great villains." },
    { id: "earthbound", title: "EarthBound", year: 1995, platforms: ["snes"], hours: 30,
      tags: ["turn-based", "party", "modern", "humour", "surreal", "story", "retro"], starter: true, aka: ["mother 2", "mother"],
      pitch: "Baseball bats, psychics, and a neighbourhood full of weirdness; funny and heartfelt until it gets quietly devastating." },
    { id: "secret-of-mana", title: "Secret of Mana", year: 1993, series: "mana", platforms: ["snes"], hours: 20,
      tags: ["action", "party", "fantasy", "exploration", "cosy", "zelda-like", "retro"], aka: ["mana"],
      pitch: "Real-time swordplay and a famous soundtrack, built for playing through with a friend beside you." },
    { id: "smrpg-snes", title: "Super Mario RPG: Legend of the Seven Stars", year: 1996, series: "mario-rpg", platforms: ["snes"], hours: 17,
      tags: ["turn-based", "party", "humour", "cosy", "retro"], starter: true, aka: ["mario rpg", "mario"],
      note: "Remade for Switch in 2023.",
      pitch: "Squaresoft's Mario crossover: timed hits, isometric puzzles, and a very silly script that still lands." },
    { id: "terranigma", title: "Terranigma", year: 1995, platforms: ["snes"], hours: 25,
      tags: ["action", "solo", "fantasy", "story", "emotional", "exploration", "zelda-like", "retro"],
      pitch: "A boy rebuilds the world piece by piece; an ambitious, melancholy action RPG that never officially reached America." },
    { id: "illusion-of-time", title: "Illusion of Time", year: 1995, platforms: ["snes"], hours: 20,
      tags: ["action", "solo", "fantasy", "story", "exploration", "zelda-like", "retro"], aka: ["illusion of gaia"],
      pitch: "A globe-trotting adventure with psychic powers and dark turns; known as Illusion of Gaia in the States." },
    { id: "secret-of-evermore", title: "Secret of Evermore", year: 1995, platforms: ["snes"], hours: 23,
      tags: ["action", "solo", "fantasy", "sci-fi", "humour", "exploration", "zelda-like", "retro"],
      pitch: "A boy and his dog tumble through a theme park's simulated worlds; an odd, atmospheric Mana cousin with alchemy instead of magic." },
    { id: "ff-mystic-quest", title: "Final Fantasy Mystic Quest", year: 1992, platforms: ["snes"], hours: 20,
      tags: ["turn-based", "solo", "fantasy", "cosy", "retro"], aka: ["mystic quest", "ffmq"],
      note: "Known as Mystic Quest Legend in Europe.",
      pitch: "Square's beginner-friendly side story, built to teach dungeon-crawling basics without ever being mean about it." },
    { id: "soul-blazer", title: "Soul Blazer", year: 1992, platforms: ["snes"], hours: 15,
      tags: ["action", "solo", "fantasy", "exploration", "cosy", "retro"],
      pitch: "Rebuild every town you save by clearing the monster lairs around it; Quintet's warm-hearted action RPG." },
    { id: "shadowrun-snes", title: "Shadowrun", year: 1993, platforms: ["snes"], hours: 20,
      tags: ["action", "solo", "sci-fi", "story", "retro"], aka: ["shadowrun"],
      pitch: "Moody cyberpunk noir with a surprisingly great soundtrack; a completely different game from the Mega Drive's Shadowrun." },
    { id: "zelda-alttp", title: "The Legend of Zelda: A Link to the Past", year: 1992, series: "zelda", platforms: ["snes"], hours: 15,
      tags: ["action", "solo", "fantasy", "exploration", "zelda-like", "retro"], starter: true, aka: ["zelda", "link to the past", "lttp"],
      pitch: "The blueprint for every Zelda after it: two overworlds, a mountain of secrets, and a perfect sense of pace." },
    { id: "harvest-moon", title: "Harvest Moon", year: 1997, series: "harvest-moon", platforms: ["snes"], hours: 25,
      tags: ["no-combat", "solo", "cosy", "social", "retro"],
      pitch: "Farm, tend animals, and win over a small town; the cosy original that started a whole genre." },
    { id: "lufia-1", title: "Lufia & the Fortress of Doom", year: 1993, series: "lufia", platforms: ["snes"], hours: 25,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "retro"],
      pitch: "A classic save-the-world quest with a famous opening and a genuinely emotional finish." },
    { id: "lufia-2", title: "Lufia II: Rise of the Sinistrals", year: 1996, series: "lufia", platforms: ["snes"], hours: 30,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "exploration", "retro"],
      pitch: "Puzzles in every dungeon and the Ancient Cave to lose weeks in; the one Lufia fans actually mean." },
    { id: "seventh-saga", title: "The 7th Saga", year: 1993, platforms: ["snes"], hours: 30,
      tags: ["turn-based", "party", "jrpg", "fantasy", "challenge", "retro"],
      pitch: "Seven heroes, seven runes, and a difficulty curve that has haunted players since 1993." },
    { id: "paladins-quest", title: "Paladin's Quest", year: 1993, platforms: ["snes"], hours: 25,
      tags: ["turn-based", "party", "jrpg", "fantasy", "surreal", "retro"],
      pitch: "A strange, colourful world where magic costs health; remembered for its art more than its balance." },
    { id: "robotrek", title: "Robotrek", year: 1994, platforms: ["snes"], hours: 20,
      tags: ["turn-based", "party", "sci-fi", "humour", "retro"],
      pitch: "Build and program a squad of robots, then send them into a very silly world; Quintet on comedy duty." },
    { id: "secret-of-the-stars", title: "Secret of the Stars", year: 1995, platforms: ["snes"], hours: 25,
      tags: ["turn-based", "party", "jrpg", "fantasy", "retro"],
      pitch: "A whole squad of heroes and a home town to rebuild between dungeons; an odd, ambitious also-ran." },
    { id: "inindo", title: "Inindo: Way of the Ninja", year: 1993, platforms: ["snes"], hours: 20,
      tags: ["turn-based", "party", "jrpg", "historical", "retro"],
      pitch: "Koei's RPG set in feudal Japan, with ninja magic, warring clans, and a world that moves without you." },
    { id: "ogre-battle", title: "Ogre Battle: The March of the Black Queen", year: 1993, series: "ogre-battle", platforms: ["snes"], hours: 45,
      tags: ["tactics", "party", "fantasy", "story", "choices", "builds", "retro"],
      pitch: "A tactics RPG about reputation as much as combat; liberate cities, and your army's alignment decides the ending." },
    { id: "breath-of-fire", title: "Breath of Fire", year: 1993, series: "breath-of-fire", platforms: ["snes"], hours: 25,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "retro"],
      pitch: "A young dragon-clan survivor and his friends; Capcom's first RPG, with a lovely day-night world." },
    { id: "breath-of-fire-2", title: "Breath of Fire II", year: 1994, series: "breath-of-fire", platforms: ["snes"], hours: 30,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "retro"],
      pitch: "Town-building, shaman fusions, and a genuinely bleak twist; many fans' favourite in the series." },
    { id: "brain-lord", title: "Brain Lord", year: 1994, platforms: ["snes"], hours: 15,
      tags: ["action", "solo", "fantasy", "exploration", "challenge", "zelda-like", "retro"],
      pitch: "An action RPG more interested in its puzzle-filled towers than its combat; a brainy Zelda cousin." },
    { id: "brandish", title: "Brandish", year: 1994, platforms: ["snes"], hours: 25,
      tags: ["action", "solo", "fantasy", "exploration", "challenge", "retro"],
      pitch: "A dungeon crawler with a rotating camera gimmick and a difficulty that does not mess about." },
    { id: "dragon-view", title: "Dragon View", year: 1994, platforms: ["snes"], hours: 15,
      tags: ["action", "solo", "fantasy", "exploration", "zelda-like", "retro"],
      pitch: "Punchy side-scrolling combat and a sprawling overworld viewed through a strange 3D window." },
    { id: "dungeon-master", title: "Dungeon Master", year: 1992, platforms: ["snes"], hours: 20,
      tags: ["action", "party", "fantasy", "exploration", "challenge", "retro"],
      pitch: "The dungeon crawler that defined real-time first-person adventuring, ported to the SNES intact." },
    { id: "eye-of-the-beholder", title: "Eye of the Beholder", year: 1994, platforms: ["snes"], hours: 20,
      tags: ["action", "party", "fantasy", "exploration", "challenge", "retro"],
      pitch: "Dungeons & Dragons crawling down dark corridors, with a party to keep alive and not much mercy." },
    { id: "lagoon", title: "Lagoon", year: 1991, platforms: ["snes"], hours: 10,
      tags: ["action", "solo", "fantasy", "story", "challenge", "retro"],
      pitch: "A Ys-style sword-and-sorcery romp with a moody soundtrack; short, tough, and very early-90s." },
    { id: "super-ninja-boy", title: "Super Ninja Boy", year: 1993, platforms: ["snes"], hours: 10,
      tags: ["action", "party", "humour", "retro"],
      pitch: "A cartoon brawler-RPG for one or two players; short, daft, and loved despite itself." },
    { id: "spike-mcfang", title: "The Twisted Tales of Spike McFang", year: 1994, platforms: ["snes"], hours: 8,
      tags: ["action", "solo", "fantasy", "humour", "retro"],
      pitch: "A tiny, stylish action RPG about a vampire hunter with a big hat; over far too soon." },
    { id: "ys-3", title: "Ys III: Wanderers from Ys", year: 1991, series: "ys", platforms: ["snes", "megadrive"], hours: 12,
      tags: ["action", "solo", "fantasy", "story", "retro"], aka: ["ys iii"],
      pitch: "Adol's side-scrolling adventure; the black sheep of early Ys, with a soundtrack people still hum." },
    { id: "ultima-runes-2", title: "Ultima: Runes of Virtue II", year: 1993, series: "ultima", platforms: ["snes"], hours: 12,
      tags: ["action", "solo", "fantasy", "exploration", "zelda-like", "retro"],
      pitch: "A top-down action RPG built for consoles, where virtue is literally your stat sheet." },
    { id: "arcana", title: "Arcana", year: 1992, platforms: ["snes"], hours: 20,
      tags: ["turn-based", "party", "fantasy", "challenge", "retro"],
      pitch: "A first-person dungeon crawler played through cards; stark, strange, and worth a look." },
    { id: "drakkhen", title: "Drakkhen", year: 1991, platforms: ["snes"], hours: 15,
      tags: ["party", "fantasy", "exploration", "challenge", "retro"],
      pitch: "An early SNES RPG with a vast, hostile world and a sky full of constellations; janky but memorable." },
    { id: "might-magic-2", title: "Might and Magic II: Gates to Another World", year: 1991, series: "might-and-magic", platforms: ["snes", "megadrive"], hours: 30,
      tags: ["turn-based", "party", "fantasy", "sci-fi", "exploration", "retro"],
      pitch: "A party of six, a huge world, and a sci-fi twist waiting at the end; a computer RPG done on console." },
    { id: "might-magic-3", title: "Might and Magic III: Isles of Terra", year: 1995, series: "might-and-magic", platforms: ["snes"], hours: 35,
      tags: ["turn-based", "party", "fantasy", "sci-fi", "exploration", "retro"],
      pitch: "The friendliest of the early Might and Magic games, with automapping and a world to chart." },
    { id: "ultima-false-prophet", title: "Ultima: The False Prophet", year: 1993, series: "ultima", platforms: ["snes"], hours: 30,
      tags: ["rtwp", "party", "fantasy", "story", "exploration", "choices", "retro"], aka: ["ultima 6", "ultima vi"],
      pitch: "The Avatar returns to Britannia to find the gargoyles have a point; a thoughtful, open-ended adventure." },
    { id: "ultima-black-gate", title: "Ultima: The Black Gate", year: 1994, series: "ultima", platforms: ["snes"], hours: 25,
      tags: ["action", "solo", "fantasy", "story", "exploration", "choices", "retro"], aka: ["ultima 7", "ultima vii"],
      pitch: "The SNES take on Ultima VII, turned into a faster action adventure without losing the world's detail." },
    { id: "wizardry-5", title: "Wizardry V: Heart of the Maelstrom", year: 1992, platforms: ["snes"], hours: 25,
      tags: ["turn-based", "party", "fantasy", "challenge", "retro"],
      pitch: "A proper dungeon crawl from the series that invented the genre, with a town to resupply in between." },
    { id: "evo", title: "E.V.O.: Search for Eden", year: 1992, platforms: ["snes"], hours: 12,
      tags: ["action", "solo", "surreal", "exploration", "builds", "retro"], aka: ["search for eden"],
      pitch: "Evolve from a fish to a dinosaur to something stranger, across five eras of Earth's history." },
    { id: "uncharted-waters", title: "Uncharted Waters", year: 1992, series: "uncharted-waters", platforms: ["snes", "megadrive"], hours: 25,
      tags: ["solo", "historical", "exploration", "retro"],
      pitch: "Trade, explore, and get rich in the Age of Discovery; Koei's RPG on the open sea." },
    { id: "new-horizons", title: "Uncharted Waters: New Horizons", year: 1993, series: "uncharted-waters", platforms: ["snes", "megadrive"], hours: 30,
      tags: ["solo", "historical", "exploration", "story", "retro"],
      pitch: "Six characters, six storylines, and the whole world to sail; the high point of Koei's seafaring RPGs." },
    { id: "obitus", title: "Obitus", year: 1994, platforms: ["snes"], hours: 12,
      tags: ["action", "solo", "dark-fantasy", "challenge", "retro"],
      pitch: "A grim first-person crawler that asks you to map a hostile world with almost no help." },
    { id: "lotr-vol-1", title: "J.R.R. Tolkien's The Lord of the Rings, Vol. I", year: 1994, platforms: ["snes"], hours: 15,
      tags: ["action", "party", "fantasy", "story", "retro"], aka: ["lord of the rings"],
      pitch: "A party of hobbits sneaking through the Shire and beyond; an unusual action RPG take on the books." },

    // Sega Mega Drive classics
    { id: "phantasy-star-2", title: "Phantasy Star II", year: 1989, series: "phantasy-star", platforms: ["megadrive"], hours: 30,
      tags: ["turn-based", "party", "jrpg", "sci-fi", "challenge", "story", "retro"], aka: ["phantasy star"],
      pitch: "A bleak, generation-spanning sci-fi epic with maze-like dungeons; the game that made Sega's name in RPGs." },
    { id: "phantasy-star-4", title: "Phantasy Star IV: The End of the Millennium", year: 1993, series: "phantasy-star", platforms: ["megadrive"], hours: 25,
      tags: ["turn-based", "party", "jrpg", "sci-fi", "story", "retro"], starter: true, aka: ["phantasy star"],
      pitch: "The Algol saga's big finish: faster and friendlier than its predecessors, with comic-panel cutscenes and a proper conclusion." },
    { id: "shining-force-2", title: "Shining Force II", year: 1993, series: "shining", platforms: ["megadrive"], hours: 30,
      tags: ["tactics", "party", "jrpg", "fantasy", "builds", "retro"], starter: true, aka: ["shining force"],
      pitch: "A grand tactical campaign with dozens of recruits and secret characters; the series at its most generous." },
    { id: "shining-darkness", title: "Shining in the Darkness", year: 1991, series: "shining", platforms: ["megadrive"], hours: 25,
      tags: ["turn-based", "party", "fantasy", "challenge", "retro"], aka: ["shining"],
      pitch: "A first-person dungeon crawl with trick walls and secret doors; the game that started the Shining series." },
    { id: "story-of-thor", title: "The Story of Thor", year: 1994, series: "story-of-thor", platforms: ["megadrive"], hours: 14,
      tags: ["action", "solo", "fantasy", "exploration", "zelda-like", "retro"], starter: true, aka: ["beyond oasis"],
      pitch: "Summon elemental spirits and brawl through dungeons in a colourful action RPG from the Streets of Rage team." },
    { id: "landstalker", title: "Landstalker: The Treasures of King Nole", year: 1992, platforms: ["megadrive"], hours: 21,
      tags: ["action", "solo", "fantasy", "exploration", "challenge", "zelda-like", "retro"],
      pitch: "Isometric adventuring with leaps of faith and a treasure-hunting plot; charming enough to forgive the dodgy platforming." },
    { id: "light-crusader", title: "Light Crusader", year: 1995, platforms: ["megadrive"], hours: 10,
      tags: ["action", "solo", "fantasy", "exploration", "zelda-like", "retro"],
      pitch: "Treasure's oddball isometric action RPG: swords, spells, and a castle full of genuinely clever puzzles." },
    { id: "phantasy-star-3", title: "Phantasy Star III: Generations of Doom", year: 1990, series: "phantasy-star", platforms: ["megadrive"], hours: 25,
      tags: ["turn-based", "party", "jrpg", "sci-fi", "story", "choices", "retro"],
      pitch: "Three generations, four possible mothers, and a family tree that changes the story; the saga's odd one out." },
    { id: "shining-force", title: "Shining Force", year: 1992, series: "shining", platforms: ["megadrive"], hours: 30,
      tags: ["tactics", "party", "jrpg", "fantasy", "builds", "retro"], aka: ["shining force 1"],
      pitch: "The original tactical campaign: recruit a quirky army, promote them, and watch permadeath bite." },
    { id: "sword-of-vermilion", title: "Sword of Vermilion", year: 1989, platforms: ["megadrive"], hours: 20,
      tags: ["action", "solo", "fantasy", "story", "exploration", "retro"], aka: ["vermilion"],
      pitch: "Sega's early action RPG, with first-person towns, side-scrolling dungeons, and a lot of ambition." },
    { id: "warsong", title: "Warsong", year: 1991, platforms: ["megadrive"], hours: 25,
      tags: ["tactics", "party", "fantasy", "challenge", "retro"], aka: ["langrisser"],
      pitch: "A grounded strategy RPG where unit matchups and commander auras matter more than grinding." },
    { id: "crusader-of-centy", title: "Crusader of Centy", year: 1994, platforms: ["megadrive"], hours: 15,
      tags: ["action", "solo", "fantasy", "exploration", "story", "zelda-like", "retro"], aka: ["soleil", "ragnacenty"],
      note: "Released as Soleil in Europe.",
      pitch: "A lovely action RPG about a boy, his animal companions, and a story that flips your expectations." },
    { id: "super-hydlide", title: "Super Hydlide", year: 1989, series: "hydlide", platforms: ["megadrive"], hours: 15,
      tags: ["action", "solo", "fantasy", "challenge", "retro"],
      pitch: "The odd, difficult black sheep of the Hydlide series; day-night cycles, hunger, and very floaty jumping." },
    { id: "fatal-labyrinth", title: "Fatal Labyrinth", year: 1990, platforms: ["megadrive"], hours: 8,
      tags: ["turn-based", "roguelite", "fantasy", "challenge", "retro"],
      pitch: "A punishing roguelike crawl where every step and every unidentified item could be your last." },
    { id: "dnd-warriors", title: "Dungeons & Dragons: Warriors of the Eternal Sun", year: 1992, platforms: ["megadrive"], hours: 20,
      tags: ["turn-based", "party", "fantasy", "exploration", "challenge", "retro"], aka: ["dungeons and dragons", "warriors of the eternal sun"],
      pitch: "A first-person D&D crawl in a lost world of dinosaurs and lizard kings, from the makers of Eye of the Beholder." },
    { id: "shadowrun-genesis", title: "Shadowrun", year: 1994, platforms: ["megadrive"], hours: 20,
      tags: ["action", "solo", "sci-fi", "story", "builds", "retro"], aka: ["shadowrun"],
      pitch: "An open-ended cyberpunk sandbox with hacking, mercenary runs, and a very different take on Shadowrun." },
    { id: "buck-rogers", title: "Buck Rogers: Countdown to Doomsday", year: 1991, platforms: ["megadrive"], hours: 25,
      tags: ["tactics", "party", "sci-fi", "exploration", "challenge", "retro"],
      pitch: "A Gold Box RPG in space: recruit a crew, fight on tactical grids, and stop the Martian menace." },
    { id: "starflight", title: "Starflight", year: 1991, platforms: ["megadrive"], hours: 30,
      tags: ["solo", "sci-fi", "exploration", "open-world", "retro"],
      pitch: "Chart the galaxy, recruit aliens, and upgrade your ship; a space epic with a genuine sense of scale." },
    { id: "immortal", title: "The Immortal", year: 1991, platforms: ["megadrive"], hours: 10,
      tags: ["action", "solo", "dark-fantasy", "challenge", "retro"],
      pitch: "An isometric dungeon of traps and grudges; harsh, clever, and unforgettably nasty." },
    { id: "cadash", title: "Cadash", year: 1991, platforms: ["megadrive"], hours: 8,
      tags: ["action", "party", "fantasy", "retro"],
      pitch: "The arcade action RPG at home: pick a class, grab a friend, and hack through a side-scrolling castle." },
    { id: "arcus-odyssey", title: "Arcus Odyssey", year: 1991, platforms: ["megadrive"], hours: 10,
      tags: ["action", "party", "fantasy", "exploration", "retro"],
      pitch: "A bright, chunky action RPG from Wolf Team, better with a second player along." },
    { id: "traysia", title: "Traysia", year: 1992, platforms: ["megadrive"], hours: 25,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "retro"],
      pitch: "A gentle, classically told RPG with battlefield-style combat and lovely art for its time." },
    { id: "exile", title: "Exile", year: 1991, platforms: ["megadrive"], hours: 10,
      tags: ["action", "solo", "fantasy", "story", "retro"],
      pitch: "A side-scrolling action RPG through history and mythology, with a story that goes places." },
    { id: "sorcerers-kingdom", title: "Sorcerer's Kingdom", year: 1992, platforms: ["megadrive"], hours: 20,
      tags: ["turn-based", "solo", "fantasy", "challenge", "retro"],
      pitch: "A solo quest with side-view battles and a difficulty curve that expects you to pay attention." },
    { id: "rings-of-power", title: "Rings of Power", year: 1991, platforms: ["megadrive"], hours: 25,
      tags: ["action", "solo", "fantasy", "exploration", "open-world", "retro"],
      pitch: "Naughty Dog's first RPG: an open world to explore long before that was a normal thing to say." },
    { id: "faery-tale", title: "The Faery Tale Adventure", year: 1991, platforms: ["megadrive"], hours: 20,
      tags: ["action", "solo", "fantasy", "exploration", "open-world", "retro"],
      pitch: "Three brothers, a murdered father, and a vast handmade world; an Amiga classic that made it to the Mega Drive." },

    // PlayStation 1 classics
    { id: "ff8", title: "Final Fantasy VIII", year: 1999, platforms: ["ps1", "pc", "ps4", "xb1", "switch"], hours: 42,
      tags: ["turn-based", "party", "jrpg", "modern", "story", "emotional", "retro"], aka: ["ff8", "ffviii", "final fantasy 8"],
      note: "On modern platforms it's the Remastered version.",
      pitch: "A military academy, a sorceress, and a love story; divisive on release, now fondly remembered for its ambition." },
    { id: "xenogears", title: "Xenogears", year: 1998, platforms: ["ps1"], hours: 60,
      tags: ["turn-based", "party", "jrpg", "sci-fi", "story", "emotional", "retro"], aka: ["xeno"],
      pitch: "Giant robots, reincarnation, and a plot that takes philosophy seriously; famously ambitious, and famously rushed at the end." },
    { id: "chrono-cross", title: "Chrono Cross", year: 1999, series: "chrono", platforms: ["ps1", "pc", "ps4", "xb1", "switch"], hours: 40,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "emotional", "retro"], aka: ["chrono"],
      note: "On modern platforms it's the Radical Dreamers Edition.",
      pitch: "Parallel worlds and a cast of dozens, with one of the finest soundtracks ever pressed to a disc." },
    { id: "vagrant-story", title: "Vagrant Story", year: 2000, platforms: ["ps1"], hours: 25,
      tags: ["action", "solo", "dark-fantasy", "story", "builds", "challenge", "retro"],
      pitch: "A dense, moody dungeon crawl through a ruined city, with weapon crafting and a story staged like a play." },
    { id: "grandia", title: "Grandia", year: 1999, platforms: ["ps1"], hours: 45,
      tags: ["turn-based", "party", "jrpg", "fantasy", "exploration", "story", "retro"],
      note: "Also remastered in the Grandia HD Collection on Switch.",
      pitch: "A proper adventure: a boy, a girl, a legend to chase, and one of the best turn-based battle systems of its era." },
    { id: "legend-of-dragoon", title: "The Legend of Dragoon", year: 1999, platforms: ["ps1"], hours: 40,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "retro"], aka: ["dragoon"],
      pitch: "Turn into a dragoon knight and time your combos in a lavish, four-disc epic that fans still campaign to revive." },
    { id: "lunar-sssc", title: "Lunar: Silver Star Story Complete", year: 1999, series: "lunar", platforms: ["ps1"], hours: 28,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "emotional", "retro"], aka: ["lunar", "silver star story"],
      pitch: "A lavish remake of the Sega CD favourite: anime cutscenes, a warm localisation, and a plucky hero chasing his Dragonmaster dreams." },
    { id: "lunar-2", title: "Lunar 2: Eternal Blue Complete", year: 2000, series: "lunar", platforms: ["ps1"], hours: 40,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "emotional", "retro"], aka: ["lunar 2", "eternal blue"],
      pitch: "The bigger sequel, with a grander adventure and a properly hissable villain; the high point of the Lunar saga." },
    { id: "vandal-hearts", title: "Vandal Hearts", year: 1997, platforms: ["ps1"], hours: 21,
      tags: ["tactics", "party", "fantasy", "builds", "retro"],
      pitch: "Konami's blood-soaked tactics debut: a revenge tale with brutal battle animations and a legendary parting choice." },
    { id: "sotn", title: "Castlevania: Symphony of the Night", year: 1997, platforms: ["ps1", "ps4"], hours: 9,
      tags: ["action", "solo", "dark-fantasy", "exploration", "builds", "retro"], aka: ["castlevania", "symphony of the night"],
      note: "On PS4 it's part of the Castlevania Requiem bundle.",
      pitch: "Alucard's inverted castle: the action RPG that defined a genre, with loot and secrets behind every wall." },

    // Sega Saturn classics
    { id: "panzer-dragoon-saga", title: "Panzer Dragoon Saga", year: 1998, platforms: ["saturn"], hours: 18,
      tags: ["action", "solo", "post-apoc", "story", "surreal", "retro"], starter: true, aka: ["panzer dragoon"],
      pitch: "A haunting ride across a ruined world on a living dragon; only a few thousand copies ever reached Europe, and it's one of the era's best." },
    { id: "shining-force-3", title: "Shining Force III", year: 1997, series: "shining", platforms: ["saturn"], hours: 32,
      tags: ["tactics", "party", "jrpg", "fantasy", "story", "builds", "retro"], starter: true, aka: ["shining force"],
      pitch: "A tactical war story told from three sides at once; the West only ever saw the first scenario." },
    { id: "shining-holy-ark", title: "Shining the Holy Ark", year: 1996, series: "shining", platforms: ["saturn"], hours: 30,
      tags: ["turn-based", "party", "fantasy", "challenge", "retro"], aka: ["shining"],
      pitch: "A first-person dungeon crawler with lovely pre-rendered corridors and a difficulty that keeps you mapping carefully." },
    { id: "dragon-force", title: "Dragon Force", year: 1996, platforms: ["saturn"], hours: 35,
      tags: ["tactics", "party", "fantasy", "builds", "retro"], starter: true,
      pitch: "Command armies of up to a hundred soldiers in real-time clashes, then recruit the enemy generals you defeat." },
    { id: "magic-knight-rayearth", title: "Magic Knight Rayearth", year: 1995, platforms: ["saturn"], hours: 15,
      tags: ["action", "party", "fantasy", "story", "zelda-like", "retro"],
      pitch: "An action RPG based on the magical-girl manga, with a warm script; also the last Saturn game released in America." },
    { id: "legend-of-oasis", title: "The Legend of Oasis", year: 1996, series: "story-of-thor", platforms: ["saturn"], hours: 12,
      tags: ["action", "solo", "fantasy", "exploration", "zelda-like", "retro"], aka: ["story of thor 2", "beyond oasis 2"],
      pitch: "The Story of Thor's prequel: tighter, prettier, and packed with spirit-summoning combat." },
    { id: "albert-odyssey", title: "Albert Odyssey: Legend of Eldean", year: 1996, platforms: ["saturn"], hours: 25,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "retro"],
      pitch: "A warm, classically told JRPG with a fine localisation and an orchestral score; the Saturn's comfort-food epic." },
    { id: "mystaria", title: "Mystaria: The Realms of Lore", year: 1995, platforms: ["saturn"], hours: 30,
      tags: ["tactics", "party", "fantasy", "builds", "retro"], aka: ["blazing heroes", "riglord saga"],
      note: "Re-released in North America as Blazing Heroes.",
      pitch: "A Shining Force-style tactics game where attack power grows with the distance you charge; a quiet Saturn gem." },
    { id: "dark-savior", title: "Dark Savior", year: 1996, platforms: ["saturn"], hours: 15,
      tags: ["action", "solo", "fantasy", "story", "choices", "retro"],
      pitch: "The Landstalker team's tangled action RPG: a prison break with parallel timelines that reshape the story." },
    { id: "guardian-heroes", title: "Guardian Heroes", year: 1996, platforms: ["saturn"], hours: 6,
      tags: ["action", "party", "fantasy", "choices", "retro"],
      pitch: "Treasure's fighting RPG: levelling, branching paths, and six-player chaos in a gorgeous brawler." },
    { id: "shining-wisdom", title: "Shining Wisdom", year: 1995, series: "shining", platforms: ["saturn"], hours: 10,
      tags: ["action", "solo", "fantasy", "exploration", "zelda-like", "retro"],
      pitch: "A Zelda-ish adventure left over from the Mega Drive years; dated, but full of charm and proper dungeons." },
    { id: "virtual-hydlide", title: "Virtual Hydlide", year: 1995, series: "hydlide", platforms: ["saturn"], hours: 10,
      tags: ["action", "solo", "fantasy", "challenge", "retro"],
      pitch: "The Hydlide saga's notorious 3D finale: clunky and ugly, but strange enough that people still talk about it." },
    { id: "hercs-adventures", title: "Herc's Adventures", year: 1997, platforms: ["saturn"], hours: 8,
      tags: ["action", "solo", "humour", "fantasy", "exploration", "zelda-like", "retro"], aka: ["herc"],
      pitch: "LucasArts' daft Greek-myth adventure: a big open world, co-op chaos, and a lot of personality." },

    // Nintendo 64 classics
    { id: "oot", title: "The Legend of Zelda: Ocarina of Time", year: 1998, series: "zelda", platforms: ["n64"], hours: 26,
      tags: ["action", "solo", "fantasy", "exploration", "story", "zelda-like", "retro"], starter: true, aka: ["zelda", "ocarina"],
      pitch: "The one that showed the world what 3D adventure could be: time travel, secrets, and a Hyrule that still feels vast." },
    { id: "majoras-mask", title: "The Legend of Zelda: Majora's Mask", year: 2000, series: "zelda", platforms: ["n64"], hours: 20,
      tags: ["action", "solo", "fantasy", "exploration", "surreal", "emotional", "challenge", "zelda-like", "retro"], aka: ["zelda", "majora"],
      pitch: "Three days until the moon falls; a stranger, sadder Zelda about masks, routines, and small human stories." },
    { id: "paper-mario-64", title: "Paper Mario", year: 2000, series: "mario-rpg", platforms: ["n64"], hours: 25,
      tags: ["turn-based", "party", "humour", "cosy", "story", "retro"], aka: ["mario", "paper mario"],
      pitch: "Mario's first paper caper, with timed-hit battles, a parade of oddball partners, and a very funny script." },
    { id: "ogre-battle-64", title: "Ogre Battle 64: Person of Lordly Caliber", year: 1999, series: "ogre-battle", platforms: ["n64"], hours: 48,
      tags: ["tactics", "party", "fantasy", "story", "builds", "retro"], aka: ["ogre battle"],
      pitch: "A stat-heavy tactics RPG about leading a revolution, with branching loyalties and unit management for days." },

    // Nintendo GameCube classics
    { id: "wind-waker", title: "The Legend of Zelda: The Wind Waker", year: 2002, series: "zelda", platforms: ["gamecube"], hours: 25,
      tags: ["action", "solo", "fantasy", "exploration", "story", "zelda-like", "retro"], aka: ["zelda", "wind waker"],
      pitch: "A flooded world, a talking boat, and a cartoon Link; the GameCube's great voyage of discovery, still gorgeous." },
    { id: "twilight-princess", title: "The Legend of Zelda: Twilight Princess", year: 2006, series: "zelda", platforms: ["gamecube"], hours: 30,
      tags: ["action", "solo", "fantasy", "exploration", "story", "zelda-like", "retro"], aka: ["zelda", "twilight princess"],
      pitch: "The moody one: a twilight realm, a wolf form, and the biggest Hyrule of its era." },
    { id: "ttyd-gc", title: "Paper Mario: The Thousand-Year Door", year: 2004, series: "mario-rpg", platforms: ["gamecube"], hours: 28,
      tags: ["turn-based", "party", "humour", "cosy", "story", "retro"], starter: true, aka: ["paper mario", "mario"],
      note: "Remade for Switch in 2024.",
      pitch: "The original paper caper: battles staged in front of an audience and some of the funniest writing Nintendo has done." },
    { id: "fe-path-of-radiance", title: "Fire Emblem: Path of Radiance", year: 2005, series: "fire-emblem", platforms: ["gamecube"], hours: 33,
      tags: ["tactics", "party", "jrpg", "fantasy", "story", "challenge", "retro"], starter: true, aka: ["fire emblem"],
      pitch: "The series' first English tactics epic: a mercenary band, permadeath, and a war told from the ranks." },
    { id: "tales-symphonia", title: "Tales of Symphonia", year: 2003, series: "tales", platforms: ["pc", "ps4", "xb1", "switch", "gamecube"], hours: 50,
      tags: ["action", "party", "jrpg", "fantasy", "story", "retro"], starter: true, aka: ["tales"],
      note: "On modern platforms it's the Remastered version.",
      pitch: "A cel-shaded world-saving quest with real-time battles and one of the genre's great casts; the GameCube's JRPG centrepiece." },
    { id: "skies-of-arcadia-legends", title: "Skies of Arcadia Legends", year: 2002, platforms: ["gamecube"], hours: 45,
      tags: ["turn-based", "party", "jrpg", "fantasy", "exploration", "story", "retro"], starter: true, aka: ["skies of arcadia"],
      pitch: "Sky pirates, airships, and a world of floating islands; a swashbuckling Dreamcast classic, polished up for the GameCube." },
    { id: "baten-kaitos", title: "Baten Kaitos: Eternal Wings and the Lost Ocean", year: 2003, series: "baten-kaitos", platforms: ["gamecube"], hours: 50,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "retro"], aka: ["baten kaitos"],
      note: "Also on Switch in the Baten Kaitos I & II HD Remaster.",
      pitch: "A world of floating islands and a card-based battle system unlike anything else; Monolith Soft at their most ambitious." },
    { id: "baten-kaitos-origins", title: "Baten Kaitos Origins", year: 2006, series: "baten-kaitos", platforms: ["gamecube"], hours: 35,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "retro"], aka: ["baten kaitos"],
      note: "Never released in Europe; also on Switch in the Baten Kaitos I & II HD Remaster.",
      pitch: "The prequel, with a streamlined card battle system and a darker revenge story." },
    { id: "ffcc", title: "Final Fantasy: Crystal Chronicles", year: 2003, platforms: ["ps4", "switch", "mobile", "gamecube"], hours: 20,
      tags: ["action", "party", "jrpg", "fantasy", "exploration", "retro"], aka: ["crystal chronicles"],
      note: "On modern platforms it's the Crystal Chronicles Remastered Edition.",
      pitch: "A co-op caravan through a world suffocating under miasma, with a chalice to babysit and memories to make." },
    { id: "pso-1-2", title: "Phantasy Star Online Episode I & II", year: 2002, series: "phantasy-star-online", platforms: ["gamecube"], hours: 35,
      tags: ["action", "party", "sci-fi", "loot", "builds", "retro"], aka: ["phantasy star online"],
      pitch: "Phantasy Star turned action RPG: four-player online hunts, rare drops, and a sci-fi world worth grinding." },
    { id: "pso-3", title: "Phantasy Star Online Episode III: C.A.R.D. Revolution", year: 2003, series: "phantasy-star-online", platforms: ["gamecube"], hours: 25,
      tags: ["turn-based", "party", "sci-fi", "loot", "retro"], aka: ["phantasy star online"],
      pitch: "The curious follow-up where card battles decide the fate of the Hunters; odd, but it works." },
    { id: "pokemon-colosseum", title: "Pokémon Colosseum", year: 2003, series: "pokemon", platforms: ["gamecube"], hours: 25,
      tags: ["turn-based", "party", "jrpg", "story", "retro"], aka: ["pokemon"],
      pitch: "A darker Pokémon story about snatching Shadow Pokémon back from a crime syndicate; doubles battles and a proper campaign." },
    { id: "pokemon-xd", title: "Pokémon XD: Gale of Darkness", year: 2005, series: "pokemon", platforms: ["gamecube"], hours: 30,
      tags: ["turn-based", "party", "jrpg", "story", "retro"], aka: ["pokemon", "gale of darkness"],
      pitch: "The better sequel: more Shadow Pokémon, a bigger region, and one of the series' rare story-driven adventures." },
    { id: "lost-kingdoms", title: "Lost Kingdoms", year: 2002, series: "lost-kingdoms", platforms: ["gamecube"], hours: 12,
      tags: ["action", "solo", "fantasy", "retro"], aka: ["lost kingdoms"],
      pitch: "FromSoftware's card-battling action RPG: collect monsters on cards and summon them in real-time scraps." },
    { id: "lost-kingdoms-2", title: "Lost Kingdoms II", year: 2003, series: "lost-kingdoms", platforms: ["gamecube"], hours: 14,
      tags: ["action", "solo", "fantasy", "retro"], aka: ["lost kingdoms"],
      pitch: "More cards, more polish, and a bigger adventure; the sequel to FromSoftware's hidden GameCube gem." },
    { id: "harvest-moon-awl", title: "Harvest Moon: A Wonderful Life", year: 2003, series: "harvest-moon", platforms: ["gamecube"], hours: 30,
      tags: ["no-combat", "solo", "cosy", "social", "retro"], aka: ["story of seasons"],
      note: "Remade in 2023 as Story of Seasons: A Wonderful Life.",
      pitch: "Grow old on a farm, raise a family, and let a whole life play out chapter by chapter." },
    { id: "harvest-moon-another", title: "Harvest Moon: Another Wonderful Life", year: 2004, series: "harvest-moon", platforms: ["gamecube"], hours: 25,
      tags: ["no-combat", "solo", "cosy", "social", "retro"], aka: ["story of seasons"],
      pitch: "A Wonderful Life's counterpart starring a girl and a different cast; the quiet alternate route." },
    { id: "harvest-moon-mm", title: "Harvest Moon: Magical Melody", year: 2005, series: "harvest-moon", platforms: ["gamecube"], hours: 30,
      tags: ["no-combat", "solo", "cosy", "social", "retro"], aka: ["story of seasons"],
      pitch: "A more classic Harvest Moon: fix up the town, court the neighbours, and earn every note of that farm." },
    { id: "lotr-third-age", title: "The Lord of the Rings: The Third Age", year: 2004, platforms: ["gamecube"], hours: 25,
      tags: ["turn-based", "party", "fantasy", "story", "retro"], aka: ["lord of the rings", "third age"],
      pitch: "A turn-based tour through the films' battles, with heroes from both sides of the war." },
    { id: "bg-dark-alliance", title: "Baldur's Gate: Dark Alliance", year: 2002, platforms: ["gamecube"], hours: 15,
      tags: ["action", "party", "fantasy", "loot", "builds", "retro"], aka: ["dark alliance"],
      note: "Re-released on modern platforms in 2021.",
      pitch: "A Dungeons & Dragons dungeon crawl with loot, levels, and a friend tagging along; arcade D&D done right." },
    { id: "gladius", title: "Gladius", year: 2003, platforms: ["gamecube"], hours: 30,
      tags: ["tactics", "party", "fantasy", "builds", "retro"],
      pitch: "LucasArts' gladiator tactics epic: train a school of fighters and rise from nobody to champion." },
    { id: "evolution-worlds", title: "Evolution Worlds", year: 2002, platforms: ["gamecube"], hours: 25,
      tags: ["turn-based", "party", "jrpg", "sci-fi", "exploration", "retro"],
      pitch: "Two Dreamcast dungeon crawlers in one, with a scrap-punk world and robots to upgrade." },
    { id: "mmx-command-mission", title: "Mega Man X: Command Mission", year: 2004, platforms: ["gamecube"], hours: 20,
      tags: ["turn-based", "party", "sci-fi", "story", "builds", "retro"], aka: ["mega man", "command mission"],
      pitch: "Mega Man X goes turn-based; a proper JRPG with mech upgrades and a story in the X timeline." },
    { id: "summoner-goddess", title: "Summoner: A Goddess Reborn", year: 2003, platforms: ["gamecube"], hours: 25,
      tags: ["action", "party", "fantasy", "story", "retro"],
      pitch: "A dark fantasy action RPG with summoning, factions, and a surprising amount of choice." },
    { id: "xml", title: "X-Men Legends", year: 2004, series: "x-men-legends", platforms: ["gamecube"], hours: 18,
      tags: ["action", "party", "loot", "builds", "retro"], aka: ["x-men"],
      pitch: "A Diablo-style X-Men brawler-RPG: build a four-hero squad and level them through the mansion's missions." },
    { id: "xml2", title: "X-Men Legends II: Rise of Apocalypse", year: 2005, series: "x-men-legends", platforms: ["gamecube"], hours: 20,
      tags: ["action", "party", "loot", "builds", "retro"], aka: ["x-men"],
      pitch: "The sequel opens up the roster and the power fantasy, with Apocalypse to stop." },
    { id: "falsebound", title: "Yu-Gi-Oh! The Falsebound Kingdom", year: 2002, platforms: ["gamecube"], hours: 20,
      tags: ["tactics", "party", "fantasy", "retro"], aka: ["yu-gi-oh", "yu gi oh"],
      pitch: "Yu-Gi-Oh as a strategy RPG: command monster armies in real-time battles across the show's world." },
    { id: "custom-robo", title: "Custom Robo", year: 2004, platforms: ["gamecube"], hours: 12,
      tags: ["action", "solo", "sci-fi", "story", "builds", "retro"],
      pitch: "Build a little robot, then battle in arenas; a sci-fi action RPG with a proper story mode." },
    { id: "medabots-infinity", title: "Medabots Infinity", year: 2003, platforms: ["gamecube"], hours: 10,
      tags: ["action", "party", "sci-fi", "builds", "retro"],
      pitch: "Customise your Medabot and duel across town; the GameCube's robot parts-collecting RPG." },
    { id: "virtua-quest", title: "Virtua Quest", year: 2004, platforms: ["gamecube"], hours: 10,
      tags: ["action", "solo", "sci-fi", "story", "builds", "retro"],
      pitch: "Virtua Fighter's world turned action RPG, with data-hunting and fighting-game roots." },
    { id: "digimon-world-4", title: "Digimon World 4", year: 2005, platforms: ["gamecube"], hours: 15,
      tags: ["action", "party", "sci-fi", "loot", "retro"],
      pitch: "A co-op dungeon crawler where your Digimon levels up with you; grind, loot, repeat." },

    // Official English releases of games whose originals stayed in Japan
    { id: "trials-of-mana", title: "Trials of Mana", year: 2020, series: "mana", platforms: ["pc", "ps4", "xsx", "switch", "mobile"], hours: 25,
      tags: ["action", "party", "jrpg", "fantasy", "story", "builds", "zelda-like"], aka: ["seiken densetsu 3"],
      note: "The 16-bit original is also in the Collection of Mana.",
      pitch: "The full 3D remake of Seiken Densetsu 3: pick three of six heroes, then take on the Mana Sword quest the West never got." },
    { id: "star-ocean-fd", title: "Star Ocean: First Departure R", year: 2019, platforms: ["ps4", "switch"], hours: 25,
      tags: ["action", "party", "jrpg", "sci-fi", "exploration", "story"], aka: ["star ocean"],
      note: "The Super Famicom original never left Japan.",
      pitch: "The sci-fi JRPG that started it all, rebuilt with real-time battles, item crafting, and a galaxy to explore." },
    { id: "dragon-quest-5", title: "Dragon Quest V: Hand of the Heavenly Bride", year: 2015, series: "dragon-quest", platforms: ["mobile"], hours: 30,
      tags: ["turn-based", "party", "jrpg", "fantasy", "story", "emotional"], aka: ["dq5", "dq v"],
      pitch: "Recruit monsters, choose a bride, and raise the next generation; the most beloved of the classic Dragon Quests." },
    { id: "romancing-saga-2", title: "Romancing SaGa 2: Revenge of the Seven", year: 2024, series: "romancing-saga", platforms: ["pc", "ps5", "ps4", "switch2", "switch"], hours: 38,
      tags: ["turn-based", "party", "jrpg", "fantasy", "exploration", "builds"], aka: ["romancing saga 2"],
      note: "A full remake of the Japan-only Super Famicom original.",
      pitch: "A generational war your heroes won't live to finish; SaGa's sprawling empire-builder, remade from scratch." },
    { id: "romancing-saga-3", title: "Romancing SaGa 3", year: 2019, series: "romancing-saga", platforms: ["pc", "ps4", "xb1", "switch", "mobile"], hours: 30,
      tags: ["turn-based", "party", "jrpg", "fantasy", "exploration", "story"], aka: ["romancing saga 3"],
      pitch: "Eight heroes, an approaching celestial flood, and SaGa's gloriously free-form way of telling a story." },
    { id: "front-mission", title: "Front Mission 1st: Remake", year: 2022, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 20,
      tags: ["tactics", "party", "sci-fi", "story", "builds"], aka: ["front mission"],
      note: "A remake of the Japan-only Super Famicom original.",
      pitch: "Wanzers, mercenary politics, and a properly grown-up mech-tactics story; the original giant-robot SRPG, remade." },

    // Zelda-likes and action adventures
    { id: "alundra", title: "Alundra", year: 1997, platforms: ["ps1"], hours: 23,
      tags: ["action", "solo", "dark-fantasy", "exploration", "story", "challenge", "zelda-like"],
      pitch: "A dream-walking hero and a village full of secrets; the closest the PlayStation got to Zelda, with some properly mean puzzles." },
    { id: "okami", title: "Okami", year: 2006, platforms: ["pc", "ps4", "xb1", "switch"], hours: 32,
      tags: ["action", "solo", "fantasy", "exploration", "story", "humour", "zelda-like"], aka: ["okami hd", "ookami"],
      note: "On modern platforms it's Okami HD.",
      pitch: "A sun-goddess wolf paints a dying world back to life; the best-loved Zelda-like not made by Nintendo." },
    { id: "tunic", title: "Tunic", year: 2022, platforms: ["pc", "ps5", "ps4", "xsx", "xb1", "switch"], hours: 15,
      tags: ["action", "solo", "fantasy", "exploration", "challenge", "zelda-like"],
      pitch: "A small fox, a lost instruction manual, and a world stuffed with secrets; a Zelda-like about the joy of figuring it out." }
  ]
};
